### ISSUE TITLE
erratic img sizing when slides aren't images

### ISSUE THREAD

**Issue by albell** [malsup/cycle2#101]
See:

http://jsfiddle.net/qbexh/

I encountered this while buildling some complex slides, and was able to boil it down to this. It's just simple slide divs containing one img and one "caption" each. (Yeah, all three slides are the same, but hey, it's just a demo.) Here are the key points:

1) The strange behavior is that when the user clicks "next", the img elements in the second and third slides are weirdly shrunken. (?!)

2) Even weirder: notice that the third slide slide is even smaller than the second. Something's iterating.

3) Even stranger, when the user switches to clicking on the "previous" button instead, all the imgs switch back to displaying at their correct full size!

4) This happens in Chrome 23, Chrome Canary, and Safari 6.0.2, but NOT in Firefox 18. (Didn't test IE.) Seems like a webkit thing.

**Comment by malsup** [comment]
http://jsfiddle.net/malsup/qbexh/1/

**Comment by albell** [comment]
Thanks. I don't really understand why: div {width:100%} needs to be explicit on on the slides, given that divs naturally expand to full width. I was always under the impression that rule was always just CSS bloat. Doesn't matter, really, I guess: it solves the problem!

**Comment by malsup** [comment]
Divs do not expand like you described when they are positioned absolutely, which they are when they're in the slideshow.
