### ISSUE TITLE
Tile Blind and Tile Slide and Youtube Videos

### ISSUE THREAD

**Issue by kosinix** [malsup/cycle2#109]
Hello mike,

Im curious if tile blind and tile slide is supported for youtube videos. It seems to be not the case.

Regards

**Comment by malsup** [comment]
I've never tried.  Seems unlikely though.  :-)

**Comment by kosinix** [comment]
Hi Mike,

Sorry my mistake. You are right the tile effects works perfectly. :-) Also my apologies for not providing links/examples.
Turns out the issue was with the previous slide's content being smaller than the next slide. http://jsfiddle.net/nDEtz/1/
Easily fixable by giving the previous slide a proper width/height and a background. http://jsfiddle.net/nDEtz/3/
Btw, while working with video slides, i noticed that the tile effects to be a bit choppy: http://jsfiddle.net/nDEtz/
Not really an issue to me, i could just turn off the tile effects when working with video slides (for my wp plugin). Just thought you might need to know. 

Cheers! stay awesome.
