### ISSUE TITLE
Problem with carousel displaying differently in Webkit v others

### ISSUE THREAD

**Issue by tyssen** [malsup/cycle2#11]
If you look at [link removed] in a Webkit browser, you'll see the top carousel (under What's On) shows four items nicely spaced (which is what I want) while the one underneath shows the first and last cut off.

View the same page in Firefox or IE and it's the second carousel that displays correctly with the first one only displaying three items.

The first carousel uses data-cycle-carousel-offset="25" while the second uses data-cycle-carousel-visible="4".

Is this a bug with the script or is it a case of user error?

**Comment by tyssen** [comment]
Any update on this?

**Comment by malsup** [comment]
@tyssen can you try adding width/height attributes to the images in your slides?  Cycle needs to perform dimension calculations in order to get the container sized correctly.

**Comment by tyssen** [comment]
That's much better, although in Firefox the four images slide right but the new that comes into view at the right isn't visible at first; it appears after the movement has stopped. In Chrome, you can see the new slide as it slides in. This is on a Mac. Haven't been able to check it out in Windows yet.

**Comment by malsup** [comment]
Removing the float:left style from ".carousel .item" should fix that.

**Comment by tyssen** [comment]
That it does. Excellent, thanks!
