### ISSUE TITLE
Two slideshows with a single prev/next

### ISSUE THREAD

**Issue by ffoodd** [malsup/cycle2#116]
Hello @malsup  !

Already send you a tweet but this is a better place.

My problem is : two slideshows & a single prev/next control thing.

When I try this declaring the same IDs on both slideshows for prev and next links, a single slideshow is working ( the last one ).

There is third slideshow ( with carousel plugin ) working alone, maybe a problem ..?

Thanks for reading, and have a nice day :)

**Comment by malsup** [comment]
Fixed with commit: f0146290fadfbad1f2dd5bef6f87245f11773dcb
