### ISSUE TITLE
this keyword in the onDestroy of jquery.cycle2.tile.js

### ISSUE THREAD

**Issue by BillyWu** [malsup/cycle2#12]
I build my interesting simple site http://www.mytintin.1866.co recently.
I use your graceful cycle2 plugin, it's a great job.
When I use tile effect, I find a strange issue:

/\* code snippet */
$('div#photoContainer').cycle({fx: 'tileBlind'});
$('div#photoContainer').cycle('resume');

$('#destroyButton').click(function(){
  $('div#photoContainer').cycle('destroy');
});
/\* end  of code snippet */

The "destroy" command will issue error message in console:
Uncaught TypeError: Object #<HTMLDivElement> has no method 'opts'

I explore the jquery.cycle2.tile.js(version: BETA-20120910)
    onDestroy: function( e ) {
        var opts = this.opts();
        opts.container.find('.cycle-tiles-container').remove();
    }
I print the this keyword, it is the opts.container itself!
I modify the code as follow:
    onDestroy: function( e ) {
        $(this).find('.cycle-tiles-container').remove();
    }
Then the error will never occur.
Expect for your verification. 
Thanks!

**Comment by malsup** [comment]
Good catch, thanks.  Fixed.
