### ISSUE TITLE
random starting slide - continue in sequence?

### ISSUE THREAD

**Issue by teapotandcake** [malsup/cycle2#123]
I know cycle2 has the option to randomize slide order completely, but is it possible to make it start at a different, random slide each time but then proceed in sequence?

It was possible to do with the old cycle, using this:
http://forum.jquery.com/topic/make-jquery-cycle-start-on-a-random-slide-but-still-run-in-sequence

but I don't know how to put that into cycle2?

**Comment by malsup** [comment]
You can still use script with C2 if you need to.  You can also use markup attributes AND script options together:

```
// give slideshow a class other than 'cycle-slideshow' so that it doesn't auto-initialize
// options will be read from markup as usual, but you can also supplement them:
$('.my-slideshow').cycle({
    startingSlide: Math.floor(Math.random() * 15), // where 15 is the slidecount 
});
```
