### ISSUE TITLE
Auto-adjust height of slideshow container based on content of each slide

### ISSUE THREAD

**Issue by daltonrooney** [malsup/cycle2#124]
I build a lot of slideshows with content that varies in height from slide to slide. Rather than pick the largest slide and set the height of the container based on that (which can leave a lot of blank space below the slideshow), I prefer to adjust the height of the slideshow container as each slide is transitioned. I think it could make sense to add this as a plugin option.

I do it like this: 

``` javascript
$('.cycle-slideshow').on( 'cycle-before', function(e, optionHash, outgoingSlideEl, incomingSlideEl, forwardFlag ) {
   $(this).height($(incomingSlideEl).height());
});
```

**Comment by malsup** [comment]
Demo:  http://jquery.malsup.com/cycle2/demo/container-resize.php
