### ISSUE TITLE
prev/next controls - what am I doing wrong?

### ISSUE THREAD

**Issue by teapotandcake** [malsup/cycle2#125]
The slideshow animates correctly in the right order when it goes on its own.

But when you click the next/prev controls, it briefly skips to the next image, and then slides to the one after?

See example here:
http://yun0.net/cycletest/

I can't find any other topics about this, but it must be something obvious that I've overlooked. Please help! I'm at my wits end.  :(

**Comment by malsup** [comment]
I think that behavior is because you've included the prevnext plugin on your page, along with the main cycle2 file.  The prevnext functionality is built into the main cycle 2 file, you only need to include it separately if you're starting off with just the "core" plugin.

**Comment by teapotandcake** [comment]
You're right! That's it, I totally misunderstood those instructions. I knew it had to be something simple. Thank you!
