### ISSUE TITLE
Add Class to Horizontal images

### ISSUE THREAD

**Issue by thibaultis** [malsup/cycle2#128]
More a question than an issue here.

I'm trying to check the width of each images in the slideshow and if the width is smaller than 630px add a class of cycle-horizontal to the parent div.

Demo is here: http://nastassiaclucas.com/wp/pictures-series/to-paint-is-to-love-again/

Where I am so far:

$( '.cycle-slideshow' ).on( 'cycle-initialized', function( event, opts ) {

```
$('.cycle-slide').find('img').each(function () {
    var $this = $(this), width = $this.width();
    if (width > 630) {
        $this.parent().addClass('cycle-horizontal');
    } else{
        $this.parent().addClass('cycle-vertical');
    }
});
```

});

Any help would be awesome.
Thanks!

**Comment by malsup** [comment]
In your case, you're binding that event too late.  When your main.js doc-ready handler executes the 'cycle-initialized' event has already fired, so your handler will never be invoked.   You can move that code to the very top of main.js, outside of the doc-ready handler.  But then you have a 2nd issue: your images do not have width/height attributes in the markup.  That means they must be fully loaded and visible for their size to be determined.  I recommend including the dimension in the markup if you have to execute code that depends on it.

**Comment by thibaultis** [comment]
@malsup - Thanks for the reply dude, makes complete sense!
