### ISSUE TITLE
autoFill with centered Y and X on none image

### ISSUE THREAD

**Issue by Colir** [malsup/cycle2#132]
Hio,
i search a way to have a full responsive slideshow according to the window size on width but also on height.

The idea is to have a result like this
http://demo.tutorialzine.com/2012/04/mobile-touch-gallery/

but with item that can not be only image...
thanks

**Comment by malsup** [comment]
These links may help:

http://jquery.malsup.com/cycle2/demo/center.php
http://jquery.malsup.com/cycle2/demo/maximize.php
