### ISSUE TITLE
Overlay fade transition - cross-fade possible?

### ISSUE THREAD

**Issue by panablue** [malsup/cycle2#133]
Is it possible to cross-fade an overlay? Maybe some other option for overlay-fx-in/out?

i made an attempt to combine a fade transition background image with scrollHorz slide content in one cycle2 instance. It's pretty good as is, but a cross-fading background image (the cycle2 overlay) would really be great.

Thank you for cycle2!

**Comment by malsup** [comment]
The default fade transition is a cross fade.   Perhaps the fadeout transition would suit you better.

**Comment by panablue** [comment]
My understanding is that the default transition for the slideshow is a cross-fade, but as in the example link (the background image is actually the overlay), the default transition for the overlay (added with the Caption2 plugin) appears to be a fade-out-then-fade-in, revealing the background briefly in between.

I'm hoping for a cross-fade on the overlay. Is that possible?

**Comment by malsup** [comment]
Sorry, I misread your question.  You're right about the overlay transitions.  I'll look into x-fade support.

**Comment by panablue** [comment]
Sorry if it wasn't quite clear - I got a little 'creative' with the overlay as the background image.

Thank you so much.

**Comment by malsup** [comment]
A cross-fade on the overlay won't be possible with the current model because only a single overlay element exists.  So the contents are faded out, replaced, and then faded back in.  There isn't an overlay div created for each slide, there is only one that is shared.

A possible workaround for you is to set the background image on the slideshow itself to match the current overlay background image.  That should "feel" more like a cross fade when it actually transitions.

```
$('.cycle-slideshow').on( 'cycle-after', function( opts ) {
    var slideshow = $(this);
    var img = slideshow.find( '.banner-background' ).css( 'background-image' );
    slideshow.css( 'background-image', img );
});
```

**Comment by panablue** [comment]
Interesting! I'll have to figure out some pre-loading, but slide to slide that might even be better than a linear cross-fade. It may just be my perception, but the effective background fade appears to begin toward the end of each slide transition - changing over as the new slide content box comes flying in.

I noticed that using "cycle-before" rather than "cycle-after" seemed to solve a minor issue where the very first transition shows a non-image background.

Thanks again!
