### ISSUE TITLE
Hide prev and next buttons when only one image

### ISSUE THREAD

**Issue by Matrix1990** [malsup/cycle2#135]
Wondering what we have to add for when a slideshow has only 1 image, hide the controls or easier, if i hide the buttons in the css, how to display them when there is more than 1 image?

Thanks

**Comment by malsup** [comment]
You can't do it declaratively, but you can add some script to handle it:

```
$('.cycle-slideshow').on( 'cycle-initialized', function( e, opts ) {
    if ( opts.slideCount > 1 ) {
        // show controls
    }
});
```

**Comment by janstieler** [comment]
Hi,
how can I use this on a nested slideshow?
I tried it on the next-event of my main slideshow but I don't know how I can get the slidecount now on my nested slideshow?

```
    $('#imageSlideshow').on('cycle-next', function(e, opts) {
        if (opts.slideCount == 1 ) {
            $('.prevSubSlide').hide();
            $('.nextSubSlide').hide();
        }
    });
```
