### ISSUE TITLE
How to Handle Progress Bar With Pause/Resume?

### ISSUE THREAD

**Issue by kosinix** [malsup/cycle2#136]
Hello Mike,

Im having an issue implementing the progress bar with pause and resume, it becomes out of sync:

http://www.codefleet.net/cyclone-slider-2/templates/dos/

Here is my snippet:

```
slideshow.on( 'cycle-initialized cycle-after', function( event, optionHash ) {
    progress.stop(true).css( 'width', 0 ).animate({ width: '100%' }, optionHash.timeout, 'linear' );
});
slideshow.on( 'cycle-paused', function( event, optionHash ) {
    progress.stop(true);
});
slideshow.on( 'cycle-resumed', function( event, optionHash ) {
    var remainingTime = (1 - (progress.width() / main.width()) ) * optionHash.timeout; //Get remaining  timeout
    progress.stop(true).animate({ width: '100%' }, remainingTime, 'linear' );
});
```

Is the timeout cleared on cycle pause or it starts all over again on cycle resume?

Best regards,
Nico

**Comment by malsup** [comment]
Last commit should fix this issue.  Check out the updated demo for example:

http://jquery.malsup.com/cycle2/demo/progress.php
