### ISSUE TITLE
Carousel different in production and development downloads

### ISSUE THREAD

**Issue by ETNyx** [malsup/cycle2#14]
I suppose the differents betwen prod and devel on download page should by only "compression" of code. If not this Issues is pointless

Anyway, if I use prod version you cant use command destroy i got this error:
[cycle2] cycle-stopped jquery.cycle2.js (line 500) TypeError: this.opts is not a function

If I use devel version, everting works fine

(btw, i append plugin into main file,...)

Greetings from Czech, E

**Comment by malsup** [comment]
Thanks for reporting this!  Looks like I forgot to push the minified files.
