### ISSUE TITLE
After removing cycle element from DOM the timeout handler continue to be invoked

### ISSUE THREAD

**Issue by itaymesh** [malsup/cycle2#143]
I've been using the jQuery Cycle library for a while and it's just wonderful!

I found out that when the cycle element is being removed from the DOM the object continue to "live" and invokes the the timeout handler on line 379.
I am using Cycle2 version 20130205.

malsup, thanks for the excellent library :)

**Comment by malsup** [comment]
Be sure to "destroy" the slideshow before removing it from the DOM.

```
$('#mySlideshow').cycle('destroy');
```

**Comment by itaymesh** [comment]
The slideshow is inside a lightbox modal that get it's content via AJAX request.
Because the modal content is rendered using same logic in the server there no guarantee that it will contains the slideshow.

**Comment by malsup** [comment]
My point is, if you start a slideshow then you need to destroy it before removing it from the DOM.  How you do that is up to you.

**Comment by itaymesh** [comment]
OK, got your point.
Tanks.
