### ISSUE TITLE
Cycle 2 Twitter demo - add the date?

### ISSUE THREAD

**Issue by Matrix1990** [malsup/cycle2#146]
I have used your example of the twitter slider for a blog. I have disabled the images so it's just the text that slides across the screen. I was wondering if there is a way to display the date ie like a tweet from "yesterday" or "1 hour ago".

Thanks!

**Comment by malsup** [comment]
The date is in the twitter response.  You can converted it to a friendlier format using something like John Resig's prettyDate:  http://ejohn.org/blog/javascript-pretty-date/
