### ISSUE TITLE
Problem with default classes

### ISSUE THREAD

**Issue by ivandotv** [malsup/cycle2#147]
I've just noticed that on the "cycle-sentiel" slide there is a class "cycle-slide-active"
As I understand, that class should mark the currently active slide, however it is attached to the sentiel slide, and also the active slide. 
I believe that is a wrong behavior. 
The issue appears also on: http://www.malsup.com/jquery/cycle2/demo/basic.php

**Comment by malsup** [comment]
Good catch, thanks.
