### ISSUE TITLE
conflict between  Mustache-style templates and Twig Template style

### ISSUE THREAD

**Issue by kspal** [malsup/cycle2#15]
Hi,

i have a problem with the Mustache-style templates used in cycle2 because i use Twig Templates which use the same Mustache-style template.

My Example :
In my file i wrote this piece of code :
<div class="cycle-slideshow" 
        data-cycle-pager-template="<a href=#><img src='{{src}}' width=50 height=46></a>"
        >

and in the browser when i look the source code, i find:

<div class="cycle-slideshow" 
        data-cycle-pager-template="<a href=#><img src='' width=50 height=46></a>"
        >

Twig replace the cycle2 template !

I found the default style for the template is in the file jquery.cycle2.tmpl.js

I could change this in the file but can we imagine to make an option for changing the template style ?

thanks

Kspal

**Comment by malsup** [comment]
See demo:  http://jquery.malsup.com/cycle2/demo/tmpl.php
