### ISSUE TITLE
Surrounding img in divs breaks slider

### ISSUE THREAD

**Issue by chinatherose** [malsup/cycle2#151]
I would like to surround all image tags in .cycle-slideshow in divs so that I can use the aria-live="polite" attribute:

div aria-live='polite' img /div

But when I add this div and change the CSS for images, the slider does not work.

Please see my two examples of working: 
http://morainestudents.com/dostalc2/workspace/cycle2-working/slider.html

and not working:
http://morainestudents.com/dostalc2/workspace/cycle2-not-working/slider.html

Any idea how I can get the slider working with these additional div tags surrounding each image?

Thank you for your assistance.

**Comment by malsup** [comment]
Check out this page:   http://jquery.malsup.com/cycle2/demo/non-image.php
