### ISSUE TITLE
Missing ">" in carousel plugin (XHTML error)

### ISSUE THREAD

**Issue by DDWeb** [malsup/cycle2#158]
Line **58** in the carousel plugin seems to be missing the last greater than sign in the closing div tag, which causes a DOM exception when the plugin is used in XHTML documents.

The offending code:

``` javascript
        // wrap slides in a div; this div is what is animated
        wrap = $('<div class="cycle-carousel-wrap"></div')
```

**Comment by malsup** [comment]
Thanks!
