### ISSUE TITLE
BUG: Carousel functionality - first slide flashing over top of last slide?

### ISSUE THREAD

**Issue by CourtFantinato** [malsup/cycle2#160]
I am using the Carousel plugin, and showing 4 slides at a time, continuously looping, with manually clicking previous and next arrows.

The Carousel works fine when clicking the next arrow, and slides move to the left. However, I am having a weird bug when clicking the previous arrow.

The active slide is the first one on the left. When I click the previous arrow, is slide to the right. To the left, would now be the new active slide slide. What happens is when the initial active slide moves to the right, I see that exact same slide to the left (where the new active slide is) just for about a second or so while the slides are moving, and then when it's complete, it flashes away and I see the slide that should be there, like it was hiding behind it.

If I remove what seems to be the double of the first slide in the developer tools, the same thing still happens but with the second slide of the Carousel "flashing" on top of the last slide.

I don't have a working example, but I have attached screen shots of how it looks on arriving at the page, during the sliding after clicking the previous (left) arrow, and then after sliding has completed.

![page-loaded](https://f.cloud.github.com/assets/2126245/374964/31c1ad24-a3ae-11e2-8112-150ab0163b9c.png)
![sliding-in](https://f.cloud.github.com/assets/2126245/374965/31d382f6-a3ae-11e2-90d4-6dd0d6dc3cd5.png)
![after-sliding](https://f.cloud.github.com/assets/2126245/374963/31aff552-a3ae-11e2-94c0-cd8167013dce.png)

Any help sorting this out would be great!

Thanks!

**Comment by ghost** [comment]
I also came across this problem.
Why the internal order of the slide queue is '3 2 1 3 2 1 1 2 3 1 2 3 1 2 3' ?
When the left most slide is the first slide, and carousel-offset is set, you will see the left two slides are the same, because the active slide is ''3 2 1 3 2 1 --1-- 2 3 1 2 3 1 2 3".
I found this fiddle from ShaunaGordon to describe this problem better: http://jsfiddle.net/VLLJX/5/
You can see two black blocks on the left. And when you click blue and next, blue becomes black.

**Comment by CourtFantinato** [comment]
Yes, it seems to be a bug with the active slide.

If you look at the Controls demo on the Carousel demo page it has the same problem: http://jquery.malsup.com/cycle2/demo/carousel.php

**Comment by CourtFantinato** [comment]
Actually, I don't know if this is actually specific the "active slide". If I choose an index number, say 5, as the starting slide, which now becomes the active slide, the problem is not there - this new starting slide is not duplicated. It is still the FIRST slide provided in the HTML that is being duplicated, whether or not it is the starting/active slide to begin with.

**Comment by CourtFantinato** [comment]
Just another observation - if I delete the first duplicate of the first slide and go through the carousel via the left arrow, the next slide (the second one) will flash over top of the last slide. If I remove that slide, and continue removing all the slides above the first, the carousel works perfect both ways.

It almost seems like an extra set is being added, if that makes any sense?

**Comment by mat2maa** [comment]
I had a similar bug that was due to the way that the wrap container is populated. See lines 74 to 82 of the Cycle2 Carousel plugin (the first Transitional Plugin here: http://jquery.malsup.com/cycle2/download/).

```
        for ( j=0; j < (opts.carouselVisible === undefined ? 2 : 1); j++ ) {
            for ( i=0; i < opts.slideCount; i++ ) {
                wrap.append( opts.slides[i].cloneNode(true) );
            }
            for ( i=0; i < opts.slideCount; i++ ) {
                wrap.prepend( opts.slides[i].cloneNode(true) );
            }
        }
```

Note: in the following [A] is the starting active slide.
Starting with the items ABC would yield CBACBA[A]BCABCABC; twice through the loop where

```
        opts.carouselVisible === undefined
```

I fixed this by changing the loop for the prepend part to

```
            i = opts.slideCount;
            while(i--) {
                wrap.prepend( opts.slides[i].cloneNode(true) );
            }
```

This now gives me the desired order ABCABC[A]BCABCABC.

Hope this helps.

**Comment by jamesmehorter** [comment]
I too am noticing this issue. Bump.

**Comment by gavimobile** [comment]
mat2maa! great fix! thanks!!! im now using your fix, but before i just removed the plugin from my header and used scrollHorz fx which worked just as good. whats the difference? anybody?

**Comment by mat2maa** [comment]
gavimobile - No problem, glad to help :)

I think if you remove the plugin and use scrollHorz then each item will be spaced as wide as their container. So in my case, I have a 100% wide container and only 200px wide images which meant there was a gap of (100% - 200px) in between each image. The plugin places the images next to each other with some margin.

If your container is the same size as your item then you wouldn't notice this as they are equivalent cases.

**Comment by gavimobile** [comment]
thanks for the explanation! its very much appreciated!

**Comment by gabrielfin** [comment]
How about this instead?

``` javascript
            for ( j=0; j < (opts.carouselVisible === undefined ? 2 : 1); j++ ) {
                wrap.append( $(opts.slides).clone(true) );
                wrap.prepend( $(opts.slides).clone(true) );
            }
```

**Comment by gavimobile** [comment]
if it aint broke, you don't fix it!

**Comment by gavimobile** [comment]
what i meant to say was thanks for your contribution! at this point in time mat2maa's fix is working and i haven't witnessed any problems.

**Comment by gteh** [comment]
thank you. mat2maa's fix worked perfectly

**Comment by gavimobile** [comment]
Maybe someone can provide the fix in a file which is meant for a production version. When I try to do this i just ruin the file.

**Comment by sebheg** [comment]
Thanks @mat2maa - your code fixes the problem as described above...!

**Comment by malsup** [comment]
Fixed per change provided by @mat2maa.  Thanks!

**Comment by gavimobile** [comment]
im really excited with the progress with this script/plugin! keep it up folks!

**Comment by gavimobile** [comment]
Also, has a production version including the fix been created? tia

**Comment by malsup** [comment]
Yes, the production version is available here:

http://malsup.github.io/min/jquery.cycle2.carousel.min.js

**Comment by gavimobile** [comment]
sweet! thanks!

**Comment by sebheg** [comment]
Thank you @malsup !

**Comment by etiennedupuis** [comment]
It still duplicate my images here.
