### ISSUE TITLE
Conflict with AddThis sharing plugin

### ISSUE THREAD

**Issue by jmkenz** [malsup/cycle2#165]
Hi there, 

I'm running an AddThis sharing plugin and Cycle2 on the same page. AddThis has a function to close it's own drop-down menu. This function is called _atw.clo(), and it causes an error when it runs. I get the following error in my console, associated with cycle2.min.js version 20121219.

Uncaught TypeError: Object _atw.clo() has no method 'apply' 

Screenshot: https://f.cloud.github.com/assets/961109/392388/cfdfca64-a77c-11e2-8a21-fc46e3856f19.jpg

Any ideas on what could be going on here?

Thank you!

**Comment by malsup** [comment]
Could you share a link that demonstrates the problem?  And use the non-minified c2 script?

**Comment by jmkenz** [comment]
Thank you malsup for your help (and for the great plugin!).  I found it was actually a problem with https://gist.github.com/ronkorving/3755461, which I had integrated into my cycle2.min.js file.  Sorry for the mixup!
