### ISSUE TITLE
PauseOnHover fails to resume when hovering first slide immediately after page load / DOM ready

### ISSUE THREAD

**Issue by sebheg** [malsup/cycle2#167]
When using the PauseOnHover option (set to "true") and hovering over the first slide after the page has loaded, the DOM is ready and Cycle has been initialized, the slideshow will not resume back to auto advance.

I've checked it with latest Chrome and Firefox on Windows 7 - head over to http://jquery.malsup.com/cycle2/demo/pause.php, load the page, hover over the orange flower to see what I mean. If you wait for the second image to load and do the hover then, the slideshow will resume.

If in doubt, set the timeout to 10000 (10 sec) to be sure that the page has loaded, the DOM is ready and the slideshow plugin has gone thru initialization...

**Comment by emartin815** [comment]
I've noticed this on mine too, when viewing it with the latest Firefox, Safari and Chrome browsers for OS 10.8.

Everything loads fine but will not initialize if the first slide has been paused on hover. It will begin only if I click on the pager for the second slide, then continues cycling through the slides as it should.

@sebheg , have you made any headway in figuring anything out on yours?

**Comment by sebheg** [comment]
@emartin815 Thanks for adding your experience to this topic! I have not made any progress looking into the problem or fixing the code, as I have no clue where to start to look at. The cycle-initialized events all get fired and I tried to trace the cycle-pause event (which gets fired on hover) but could not locate the piece of code that causes our problem... @malsup could you please look into this? Thank you! :smile:

**Comment by sebheg** [comment]
thanks for the fix @malsup ! I've downloaded the latest version and it is working now :smile:
