### ISSUE TITLE
cycle-initialized and firefox

### ISSUE THREAD

**Issue by Colir** [malsup/cycle2#170]
Hi,
i'm trying to do a fading appearition of my slideshow with the use of the cycle-intialized event.
This event is always triggering in Chrome, but no in firefox....

**Comment by malsup** [comment]
Can you created a fiddle or plunkr that shows the problem?

**Comment by Colir** [comment]
http://jsfiddle.net/Colir/UFzG4/1/

**Comment by malsup** [comment]
Actually, jsfiddle isn't a good example because it wraps your script in a window load event, which is too late.  Here's an example:

http://plnkr.co/edit/acilUQ?p=preview

**Comment by Colir** [comment]
Ok i found my mistake. 
I 've bind the Init event after the Cycle déclaration (i use js to init Cycle)...so in local, as my images are quickly load, Cycle been init before the init event handler was bind.

sorry. thanks for your support
