### ISSUE TITLE
feature request: 1 pageing for two elements (in cycle2)

### ISSUE THREAD

**Issue by gavimobile** [malsup/cycle2#176]
hey folks, 

i currently have two carousels synchronized with each other. they each do a different effect when changing to the next slide which is exactly what i want. Now, i want one paging for both carousels. i cannot seem to find this anywhere on the website.

i assume this would need to be created via jquery custom code rather than in the element tags as shown here http://jquery.malsup.com/cycle2/demo/pager.php#adv-custom

if this feature is already possible maybe someone can at least point me in the right direction on how to accomplish this. here is my current code
http://pastebin.com/QvNMwjE1

also another few requests if possible.
it would be great if we had some more effects such as diagonal fade-ins or diagonal slide-in.

an additional request would be to have a feature which will allow the scrolling of the carousel via control of the mouse.
if the mouse roller is moved while on the carousel then the carousel will move in that direction.

**Comment by malsup** [comment]
Here's an example of one pager controlling two slideshows:

http://jquery.malsup.com/cycle2/demo/pager-two.php

**Comment by gavimobile** [comment]
mike thanks for your reply! i already had an example like this working, however any type of changes i try to make to the pager doubles the amount of bullets. can you give the same example with using an image rather than the default bullets?

**Comment by malsup** [comment]
It's the same idea, you set the first slideshow's pager template to whatever you want, and then set the second slideshow's template to nothing so that it uses the same pager elements.

http://jquery.malsup.com/cycle2/demo/pagers.php

**Comment by gavimobile** [comment]
wow!!! thank you!!!! i thought i tried every single combination!!! hope we can see some new effects in the new future!!!
