### ISSUE TITLE
carousel not working

### ISSUE THREAD

**Issue by webyonet** [malsup/cycle2#177]
how to carousel on "a" element ?
sample: (not working)
&lt;ul class=&quot;slideshow&quot; 
    data-cycle-fx=carousel
    data-cycle-timeout=1000
    data-cycle-slides=&quot;&gt; li&quot;&gt;
      &lt;li&gt;&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;assets/img/framework1.png&quot;/&gt;&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;assets/img/framework1.png&quot;/&gt;&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;assets/img/framework1.png&quot;/&gt;&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;assets/img/framework1.png&quot;/&gt;&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;assets/img/framework1.png&quot;/&gt;&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;assets/img/framework1.png&quot;/&gt;&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;assets/img/framework1.png&quot;/&gt;&lt;/a&gt;&lt;/li&gt;
    &lt;/ul&gt;

**Comment by matheusvetor** [comment]
Does not work for me too. strangely, I copied the example from the project page and also does not work.

**Comment by gavimobile** [comment]
carousel works for me, it did seem to be a bit buggy though. when i used the navigation some from the first to the last slide or last to first slide it would skip sometimes. i decided to use "scrollHorz" instead.
could you guys post a link to where your testing, or a demo? i'd like to take a look at it.
