### ISSUE TITLE
transition skipping timeout issue 

### ISSUE THREAD

**Issue by jdeblank** [malsup/cycle2#18]
When loading images from a CDN and using the loader plugin, every 2nd slide seems to skip the timeout between transitions. I can't reproduce the symptoms without "data-cycle-loader=true". 

http://jsfiddle.net/5TKYh/5/

Replicated in Chrome 24, Firefox 15, Safari 5.1.7.

**Comment by jdeblank** [comment]
thanks @malsup. I sent you a 'beer'. :)

**Comment by malsup** [comment]
Thank you!
