### ISSUE TITLE
First slide ignores 'timeout' parameter 

### ISSUE THREAD

**Issue by jesstech** [malsup/cycle2#186]
http://jsbin.com/ovuxom/1/

In the jsbin example above, all slides have a timeout of 10000 (10s) applied to their individual slide elements—but the first slide transitions after the default 4000ms (4s).  After looping through all slides and back to the first, the timeout works as expected.

I anticipate the response here will be to use the `delay` parameter to fix this for the first slide, but here's my rebuttal: according to the docs, the `delay` parameter needs to be applied to the slideshow container element.  I use Cycle2 in a lot of ExpressionEngine templates, where grabbing a custom field outside of the loop that creates the individual slide elements is a real nightmare.  I don't have the flexibility to easily grab the first slide's timeout and attach it to the slideshow container element as `data-cycle-delay`, which is why I apply the timeout to the individual slide elements instead.

I think most people would expect the `timeout` parameter to apply to _all_ slides, including the first, since it is an option that can be applied per-slide.

**Comment by malsup** [comment]
Yeah, that's a big. Will fix.
