### ISSUE TITLE
DIV Slideshow with custom pager with titles...

### ISSUE THREAD

**Issue by jschalcyon** [malsup/cycle2#187]
I didn't know where to ask for help and was wondering if someone could help me with an example of a DIV slideshow with a pager that has custom titles. 

I can get get an image slideshow to work the way I want it to. But as soon as I add DIVs to the mix, it doesn't work right. I can figure it out if someone if someone had an example I could use. 

Please feel free to ask for any additional information. Thank you for taking your time with this question.

**Comment by hhoang** [comment]
http://jquery.malsup.com/cycle2/demo/non-image.php

You need to specify 
  data-cycle-slides="> div"

Here's a working example with pager:
http://jsfiddle.net/6E5zq/

**Comment by jschalcyon** [comment]
hhoang resolved the issue for me. Thank you so much! I really appreciate the help.
