### ISSUE TITLE
Unexpected NaN breaks cycle2 startup.

### ISSUE THREAD

**Issue by programmin1** [malsup/cycle2#192]
In some cases, pause-on-hover can keep cycle2 from starting, when mouse was over the slideshow while the page was loading.

I tracked it down to an unexpected NaN, in the pause function. If you change
`if ( opts._remainingTimeout < 0 )`
to
`if ( opts._remainingTimeout < 0  || isNaN(opts._remainingTimeout))`

it works. Not sure if this is the best way to solve it though.?

**Comment by malsup** [comment]
This was already fixed.

https://github.com/malsup/cycle2/commit/dd041ee2fd5d73ad7939a4b1cc5f40cacd89eacd
