### ISSUE TITLE
Options "centerHorz" and "centerVert" only working after window resizes.

### ISSUE THREAD

**Issue by MaDDmin** [malsup/cycle2#197]
Hi!
 Well, the site is http://bit.ly/12xRPdD (just click on "CATÁLOGO" to show them up). The slides are mounted "on the fly" by an AJAX call. The idea is to have every slide image centered from the beginning but it only works AFTER the window is resized. How can I solve this???
Thank you!!!

**Comment by malsup** [comment]
I'm not sure what to look at on that link.  Seems to work fine when I view it.

**Comment by MaDDmin** [comment]
Wow! Okay, maybe I should have mentioned that the big banner IS NOT the problem. I'm sorry about that, my bad.
The problematic sliders are the ones that show when "CATÁLOGO" is clicked. The slides' images are not centered when they are shown. You will notice the change (in some pictures more than others) if you resize the window with your eyes put on them. I found this https://github.com/malsup/cycle2/issues/35 but that workaround doesn't seem to work for me.

Thanks again!

**Comment by malsup** [comment]
I think that's because those slides are hidden when cycle runs, so it can't correctly calculate the dimensions.  If you can trigger a resize event on the window after that reveal animation it will probably work fine.

**Comment by MaDDmin** [comment]
Solved!
Thanks.
