### ISSUE TITLE
Problems with timeout and delay

### ISSUE THREAD

**Issue by craftycoding** [malsup/cycle2#199]
I'm having some trouble getting delay and timeout to play well together. Basically I have 18 slideshows, each with 3 pictures and I want each one to change sequentially. So I have a delay array like this..

```
$delay = array('0','1000','3000','5000','7000','9000','11000','13000','15000','17000','19000','210000','23000','25000','27000','29000','31000','33000');
```

Then in each slideshow call I have..

```
<div class="cycle-slideshow" 
data-cycle-fx=fade
data-cycle-timeout=<?php echo 36000; ?>
data-cycle-speed = 2000
data-cycle-delay = <?php echo $delay[$offset]; ?>>
```

The timeout is set so that only one image will change at a time i.e 1800*2. However the delay isn't working as expected. When the page loads I would like the transition to start but it waits 36000 before anything changes. Isn't it supposed to be the delay that sets when the slider starts and timeout is once it's got started or am I doing something wrong here? Any help you could give would be much appreciated.

Thanks,
Lisa

**Comment by malsup** [comment]
"delay" is the amount of time to add before beginning the first transition.  "timeout" is the amount of time between transitions.

**Comment by craftycoding** [comment]
Hiya,

Thanks for your reply however I'm still confused as how I can get it the way I want. The page is doing exactly what I want now except.. I have to wait 36000 before it starts doing it. Something here is a little funky, I would like the swapping to start already at 0 but no matter what I change the delay to (even 0) it is still waiting 36000 before it starts which makes me think there is a bug either in my logic or in the script. Thank you for your time, much appreciated.

**Comment by malsup** [comment]
If you want a slideshow to start right away, give it a negative delay value.

```
<div class="cycle-slideshow" data-cycle-timeout=3600 data-cycle-delay=-3600 ...>
```

**Comment by craftycoding** [comment]
Hiya,

I have done that. On the link I sent you can see that the first slideshow has a delay of -3600 yet it still doesn't start.

**Comment by malsup** [comment]
No, what you did is this:

```
<div class="cycle-slideshow" data-cycle-timeout="36000" data-cycle-delay="-3600" ...>
```

The formula for the first transition is ( timeout + delay ) which in your case is:  36000 - 3600 = 32400

**Comment by craftycoding** [comment]
Hello there,

Thanks for all your help. When I set the first one to -36000 it didn't work but when I set -36500 it did work and now they're all working happily. I just sent you some dosh for all your help. Thanks very much!

**Comment by malsup** [comment]
Thank you!
