### ISSUE TITLE
Cannot read property 'autoSelector' of undefined when using async

### ISSUE THREAD

**Issue by leon** [malsup/cycle2#2]
When I include cycle2 using:

``` html
<script src="..." async></script>
```

I get `Uncaught TypeError: Cannot read property 'autoSelector' of undefined`

If I remove the async property the script works fine.

I did some debugging, and it's looks like you need to move the domready function to the bottom of the script
https://github.com/malsup/cycle2/blob/master/jquery.cycle2.core.js#L496

because it's firing before the default are set
https://github.com/malsup/cycle2/blob/master/jquery.cycle2.core.js#L551

**Comment by malsup** [comment]
Good catch, thanks.  Fixed now.
