### ISSUE TITLE
Random slide order option?

### ISSUE THREAD

**Issue by panablue** [malsup/cycle2#20]
(I didn't see any other mention of this but it may already have been addressed as I imagine it would be a popular feature.)

I don't see an option to display slides in random order. I was able to use an extra bit of jQuery to randomize the slide elements before the slideshow begins, but are there plans to include a random option as in the original Cycle?

Thank you for the continued development of all your plugins, particularly these simple and flexible rotators! Cycle2 is great!

**Comment by malsup** [comment]
http://jquery.malsup.com/cycle2/api/#random
