### ISSUE TITLE
cycle options does not clean from jquery's cache upon destroy.

### ISSUE THREAD

**Issue by mikila85** [malsup/cycle2#201]
opts.container.removeData( 'cycle.opts' );
on line 909, does not work!
it's purpose is to clean the jquery cache and enable reading of new data() settings from attributes, but in fact it does not. destroy+cycle() loads the cached options.

**Comment by mikila85** [comment]
right now i do:
for (var dat in $.cache){if($.cache[dat]["data"]!=undefined)$.cache[dat]=null;}
but it is a hacky way to fix the problem.

**Comment by malsup** [comment]
Fixed.

**Comment by mikila85** [comment]
oh great! malsup your the best! thank you :) :+1:
