### ISSUE TITLE
active slide trouble when using remove

### ISSUE THREAD

**Issue by Colir** [malsup/cycle2#207]
Hi, 
i 've a problem when i use $galerie.cycle('remove',0).
I want to remove prev slide in a cycle when the transition to next slide is perform.
But when i do that, my staying slide lost is active class...
thanks

**Comment by spez86** [comment]
Yep, seeing the same thing.

Here's a codepen version:
http://codepen.io/anon/pen/cLxAF

Nothing crazy, but shows how the active slide is lost the moment after a transition completes and a slide is removed.

Using the nav thereafter works fine for the remained of the slideshow.

Seems like a bug inside of "update view"
