### ISSUE TITLE
Non-Circular Carousel Next goes beyond slideCount + carouselVisible

### ISSUE THREAD

**Issue by mattjanssen** [malsup/cycle2#21]
Go to http://jquery.malsup.com/cycle2/demo/carousel.php **Non-Circular Demo** and click _Next_ four times while at the end of the slides. Now click _Prev_. It won't go back until you click _Prev_ four times.

The problem: `currSlide` advances beyond `slideCount + carouselVisible` and causes unexpected behavior.

My fix (applied outside of the library) modified from **jquery.cycle2.js** line 696:

``` javascript
var c2 = $.fn.cycle;
$.extend( c2.API, {
    next: function() {
        var opts = this.opts();
        var count = opts.reverse ? -1 : 1;
        if ( opts.allowWrap === false && ( opts.currSlide + count ) > opts.slideCount - opts.carouselVisible )
            return;
        opts.API.advanceSlide( count );
        opts.API.trigger('cycle-next', [ opts ]).log('cycle-next');
    }
});
```

Notice `==` changed to `>` and `- opts.carouselVisible` added.

**Comment by malsup** [comment]
Thanks for finding and providing a fix!  :-)

**Comment by mattjanssen** [comment]
Thanks for you work on this project!
