### ISSUE TITLE
Problems with mac

### ISSUE THREAD

**Issue by craftycoding** [malsup/cycle2#213]
Hiya,

I have a crazy amount of cycle2's on one page and it works great in every browser and resolution on Windows but my friend on a mac says they are flickering and get white lines while at certain sizes on mac (safari, firefox and chrome on mac all have this problem). Is this a known issue or just general buginess with jquery, css3 and mac's? Thanks for any advice you can give me. A demo of the page is http://customers.craftycoding.com/maggie/ there.

Thanks again!

**Comment by malsup** [comment]
I just loaded your page on Chrome for Mac and it looks fine.  I do all of my development on a Mac so if there was an issue I think I'd know about it.

**Comment by craftycoding** [comment]
Ok that's great to know. I wonder what's up with her computer then gah.
Thanks so much for the info, I'll pass it along to my customer.

Thanks,
Lisa

On Tue, Jun 4, 2013 at 3:10 PM, Mike Alsup notifications@github.com wrote:

> I just loaded your page on Chrome for Mac and it looks fine. I do all of
> my development on a Mac so if there was an issue I think I'd know about it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/malsup/cycle2/issues/213#issuecomment-18904884
> .

## 

http://www.craftycoding.comhttp://www.craftycoding.com
puh. 050-3139531

**Comment by malsup** [comment]
I also opened that page with FF, Safari and Opera (all Mac) and it works fine in all of them.  However, if your friend has a slow computer then displaying 18 slideshows may be causing display issues.

**Comment by craftycoding** [comment]
Yes must be something like that. I'm glad it's just her comp then because
it works beautifully everywhere else so I was a bit miffed and I also don't
have a mac so that made debugging pretty much impossible. Either way I
appreciate your help, she'll just have to live with it unfortunately.

Thanks,
Lisa

On Tue, Jun 4, 2013 at 8:06 PM, Mike Alsup notifications@github.com wrote:

> I also opened that page with FF, Safari and Opera (all Mac) and it works
> fine in all of them. However, if your friend has a slow computer then
> displaying 18 slideshows may be causing display issues.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/malsup/cycle2/issues/213#issuecomment-18923664
> .

## 

http://www.craftycoding.comhttp://www.craftycoding.com
puh. 050-3139531
