### ISSUE TITLE
Carousel Option for Variable Image Widths?

### ISSUE THREAD

**Issue by attheshow** [malsup/cycle2#215]
Is there any way to change the cycle to where the heights of the images can be consistent with variable widths? I'm dealing with cover images that are pulled in from Amazon and are a variety of sizes. Right now we've got the cycle making the widths all the same in order for the carousel to work correctly. If I try making the heights the same and not the widths, images get chopped off and the carousel doesn't progress to the end of the images correctly since everything's based off of the single sentinel image.

Also, please let me know if there are any hints you can give me on how I could code this into the plugin myself. I'd love to be able to help out with a patch.

![screen shot 2013-06-05 at 12 05 21 pm](https://f.cloud.github.com/assets/191008/620517/2cf644d6-cee6-11e2-91a1-d1ac41fda48e.png)

**Comment by sebheg** [comment]
I finally got it working, using the "data-cycle-loader" option, set to "wait".

Like so:

$('#slideshow')
  .cycle({
     fx: 'carousel',
     speed: 500,
     timeout: 3000,
     pauseOnHover: true,
     loader: 'wait'
  });

**Comment by malsup** [comment]
Thanks for the update, glad to hear it's working for you.
