### ISSUE TITLE
Video demo does not work at the moment

### ISSUE THREAD

**Issue by kosinix** [malsup/cycle2#221]
Hello Mike,

Just wanted to report that http://jquery.malsup.com/cycle2/demo/video.php seems to be not working at the moment:
![c2video](https://f.cloud.github.com/assets/1096465/673792/be38b614-d8c2-11e2-98f6-29de400989bc.png)

Console says: http://jquery.malsup.com/cycle2/jquery.cycle2.video.js 404 (Not Found) 

Thanks
Nico

**Comment by malsup** [comment]
Thank you.
