### ISSUE TITLE
Tweets not working

### ISSUE THREAD

**Issue by freddyx** [malsup/cycle2#222]
I've used cycle2 a couple of months with Twitter. But now it is not working anymore.
Even your example on http://jquery.malsup.com/cycle2/demo/twitter.php isn't working.

Tried this link http://search.twitter.com/search.json?callback=?&q=cycle2 and got: 

{"errors": [{"message": "The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.", "code": 68}]}

**Comment by malsup** [comment]
Twitter recently retired their v1 search API so that demo is no longer valid.

**Comment by freddyx** [comment]
But is it possible to use the new v1.1 API?

**Comment by malsup** [comment]
No, the new API requires authentication.  You can try using a workaround like this:

http://jasonmayes.com/projects/twitterApi/
