### ISSUE TITLE
<a href="xxxxx" target="_blank"><img /></a> like this,but dosn't work,who can help me?

### ISSUE THREAD

**Issue by MrDian** [malsup/cycle2#223]
![a](https://f.cloud.github.com/assets/3294028/690667/6b5075ee-db20-11e2-9f4a-363f0b029d17.png)

**Comment by ralves-dev** [comment]
```
data-cycle-slides="> a"
```

You'll have to use that because the direct children are `a` elements, not `img` elements that are the default option on cycle2

**Comment by MrDian** [comment]
thanks a lot!

**Comment by ralves-dev** [comment]
If your issue is solved, please close this issue on the button next to the Comment one. Thanks!
