### ISSUE TITLE
Paging breaks callback vars

### ISSUE THREAD

**Issue by stikoo** [malsup/cycle2#23]
This issue has been noted when the carousel option is used.

I've discovered a bug that  makes the curr value for the cycle-after callback point to the wrong slide in the following instances...

a: you click on a paging item before the first slide has transitioned( if using a timeout value).
b: when not using a timeout.

Strangely, the bug fixes itself after you've transitioned through all the slides!

**Comment by malsup** [comment]
I'm not able to duplicate this issue with latest code.  Can you please retest?  Thanks.
