### ISSUE TITLE
Accessible carousel pager

### ISSUE THREAD

**Issue by stevenMouret** [malsup/cycle2#234]
I want to make an accessible carousel but I'm stuck on pager.
When an item from the pager is enabled by default it has the class "cycle-pager-active". I wish to add to the alternative of my image an information to understand that it is active.

Here the result that I want:

```
<ul class="cyclePager">
    <li class="cycle-pager-active"><button type="button"><img alt="1 active" src="active.png"></button></li>
    <li class=""><button type="button"><img alt="2" src="notactive.png"></button></li>
</ul>
```

I do not know if this is possible with Cycle2, May be with API?

Thx for your help.

**Comment by malsup** [comment]
You can bind the cycle-after event to make whatever changes to the DOM you need.

http://jquery.malsup.com/cycle2/api/#events

**Comment by stevenMouret** [comment]
Hello Malsup,

Thx for your answer.

I advanced on my carousel but I did not understand a thing.
Below is an example for better understanding.
http://jsfiddle.net/korigan/D88pY/1/

My goal is to change the image and modify pager alternative image when the class cycle-pager-active exist.
This works but as you can see it is shifted.

I use cycle-before event but it starts after.
If you click on a button that is the previous that is active.
