### ISSUE TITLE
Sentinel slide appearing as blank slide

### ISSUE THREAD

**Issue by ChrisGreenhough** [malsup/cycle2#237]
I had an issue with the sentinel slide appearing as a blank slide in my slideshow. This was running a default Cycle set-up with the exception of using a div instead of an img. In the end I found that specifying data-cycle-auto-height manually was the only way I could seem to overcome this. I'm running jquery 1.9.1.

**Comment by jgadbois** [comment]
I'm having this same problem - haven't found a workaround yet

**Comment by jgadbois** [comment]
FYI this happens for me with auto-height "calc" and index-based auto-height

**Comment by ChrisGreenhough** [comment]
Yep I was really tearing my hair out, assuming it was something stupid I'd done in the JS or CSS elsewhere on the site page (quite possible in my case). But in the end I just couldn't fathom it and had to sidestep the problem. As a funny aside, I did chuckle / grimace when I finally worked out why one of the other slides was appearing as blank… The ad blocker had deemed the image an advert and hidden it. I was baffled by this until I twigged it had made this decision based solely on the file name (ad naming conventions, it seems) so once I changed the file name it was OK. Although I also disabled ad blocking to be certain this wasn't the reason behind the blank sentinel slide.

**Comment by jgadbois** [comment]
@malsup - any chance you can look at this?

**Comment by malsup** [comment]
Can you post a link to a simple test page that shows the problem?

**Comment by jgadbois** [comment]
Here's a page we're seeing the issue on.  Notice how the slideshow blanks out with the sentinal slide.

http://www.bookster.com/jennifer-watson

Here's the markup and it's just instantiated with a `.cycle()`

```
              <ul class='floated-items offers clearfix cycle-slideshow'
                data-cycle-next=".next"
                data-cycle-prev=".prev"
                data-cycle-timeout="3000"
                data-cycle-speed="1000"
                data-cycle-slides="li"
                data-cycle-pager-template="<span>&nbsp;</span>"
                data-cycle-pager=".cycle-pager"
                data-cycle-auto-height="calc"
                data-cycle-hide-non-active="false"
                data-cycle-pause-on-hover="true"
              >
                  <li class='mod-mini-offering hero'>
                    <div class='text'>
                        <div class='title'><a href="/jennifer-watson/offers/37">&quot;Signed hardcover book&quot;</a></div>
                        <div class='clearfix'>
                          <div class='mod-offer-quants'>
                          <div class='price'>$45</div>
                          <div class='available'>425 spots left!</div>
                       </div>

                       <a class="button black" data-fancybox-type="ajax" href="/orders/new?offering_id=37" rel="fancybox">Buy now</a>
                     </div>
                   </div>

                  </li>
```

**Comment by malsup** [comment]
I'm not able to duplicate this issue.  http://jquery.malsup.com/cycle2/demo/test-sentinel.php

Can you try using the latest version of C2?

**Comment by jgadbois** [comment]
I still get it with the latest version of C2.  Also changed the `<li>` contents to a simple `<img>` tag and got the same results.  

Watching developer tools, the first slide does have an opacity of 1 when the slideshow starts but is still invisible until the next time around the slideshow.  It could possibly be a z-index issue, but that seems to be set correctly.  

It definitely appears to be related to the sentinel because if I set a ratio for auto-height, then the problem goes away.

**Comment by jgadbois** [comment]
Ok tracked down the problem.  I had the following css:

```
li { display: none; }
li:first-child { display: block; }
```

I'm guessing since the sentinel moved to the front of the list it added a `display: none` to the first slide.  I just added an additional class name to the first slide to keep it visible during initialization and that solved the problem.

**Comment by malsup** [comment]
Thanks for the update, John.
