### ISSUE TITLE
for(X) {obj.cycle("destroy"); obj.cycle();} makes overlay transition effect flicker X-times

### ISSUE THREAD

**Issue by mikila85** [malsup/cycle2#238]
http://jsfiddle.net/9cRE3/

try it, press Destroy, cycle.
the overlay transition effect will repeat as many times as you do that.
i let my users edit theyr slideshow, when saved i need to destroy (clean up the code) and then cycle again.

makes it every time a user saves he's work, the cycle starts flickering more and more.

**Comment by malsup** [comment]
Get rid of the competing display styles:

```
.cycle-overlay { 
    display:none!important;
}

.innerSlideShowContainer[data-cycle-caption-plugin=caption2] .cycle-overlay{
    display:block!important;
}
```

**Comment by mikila85** [comment]
Thanks alot mike :)
