### ISSUE TITLE
Feature: Carousel: advanceTo, goBackTo (as variants of goto)

### ISSUE THREAD

**Issue by Laubeee** [malsup/cycle2#244]
I'd like to use a carousel as Pager that is looping. So when I have 6 slides and I click on slide 7 (which is actually slide 1), goto slides "back" to 1 instead of going forward to the next instance of slide 1 (which would be 7 in that example)

So some parameter in GoTo or a new function would be lovely to handly this behavior

**Comment by Laubeee** [comment]
Oops, didn't see the "advanced API"... sorry!

**Comment by IonBazan** [comment]
Could you please provide a code snippet?
I am trying to achieve this effect too.

**Comment by Laubeee** [comment]
$('.cycle-slideshow').data('cycle.API').advanceSlide(3); should do.
