### ISSUE TITLE
Can i have a div inside the cycle-slideshow div?

### ISSUE THREAD

**Issue by Matrix11** [malsup/cycle2#247]
I am using your plugin and creating a dropdown list that when an option is selected, the images related to the div are shown (basially this: http://code-tricks.com/change-div-on-changing-drop-down-using-jquery/ )

I have my code all prepared for the slideshow but i need to wrap a div around the images as these will be changed depending on the dropdown selection. Is it possible to have a div inside the cycle slideshow container as it's going to have NO style just id attribute for jQuery to listen?

Here is my code to how id like it positioned: http://jsfiddle.net/

**Comment by malsup** [comment]
Sure, you just need to adjust the "data-cycle-slides" option as discussed  here:  

http://jquery.malsup.com/cycle2/demo/non-image.php

In your case, you probably want:  data-cycle-slides="> div > img"

**Comment by Matrix11** [comment]
This is great but the small thumbnails from the hidden div dont hide and when gallery is selected they both show? Sorry if this is a simple issue just confused with what i can can't do with the plugin :)
