### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by senecan** [malsup/cycle2#256]
Cycle2 is working fine in Chrome and IE, but I'm encountering a problem in Firefox. On transition, the width of the image fading out is compressed by a small but noticeable amount, and the image fading in starts from the compressed width and then expands to its full width. The compression/expansion occurs only on the right side of the image. I tried to correct this problem using the loader option (both "true" and "wait" modes)(http://jquery.malsup.com/cycle2/demo/loader.php), but without success. Any help would be much appreciated.

**Comment by malsup** [comment]
Are you seeing that behavior on any of the demo pages?

**Comment by senecan** [comment]
Thanks for your reply.

After playing around with Firebug for a while, I think I've figured out what's going wrong. The problem seems to lie in how the default styles are interacting with Bootstrap. Now that I've deleted the "width: 45%" declaration from .cycle-slideshow, everything is working fine.

**Comment by malsup** [comment]
Thanks for the update.
