### ISSUE TITLE
Event "cycle-update-view" is not triggered on first load

### ISSUE THREAD

**Issue by vaxul** [malsup/cycle2#257]
Hi,

first thanks for this wonderful jQuery Plugin! =)

I have a simple slideshow and this code:

``` javascript
$('#example')
    .on('cycle-update-view', function(event, optionHash, slideOptionsHash, currentSlideEl){
        console.log(currentSlideEl);
        var data = $(currentSlideEl).attr('data-medium');
    });
```

If I watch the console, on initial page load "[cycle2] --c2 init--" is outputted. I expected the event 'cycle-update-view', but it isn't triggered. I try to act with the "currentSlideEl". At slide transition it's triggered correctly. 

In the api-docs is written "Triggered after initialization". That's how it should be?

Best regards,

vaxul

**Comment by malsup** [comment]
Seems to work on this example:  http://jquery.malsup.com/cycle2/demo/test-update.php

Perhaps you're binding that event handler too late?

**Comment by vaxul** [comment]
Hi, thank for your quick response.

How can the binding be to late? Or in other words: How can I make sure, that the binding is not to late?

P.S. I use v20130801 of cycle2

**Comment by malsup** [comment]
The binding is too late if it occurs after the event has already fired.  If you're binding in a doc-ready handler then that is probably too late.

**Comment by vaxul** [comment]
I see. Of course I used:

``` javascript
$(function(){

});
```

So I moved the code and now it works. 

This means I can't use this event, if my JavaScript is within the head-tag? Fortunately I have my JS-Files alway before the closing body. =)

Big thanks for your quick help!

**Comment by malsup** [comment]
If your js is within the head tag then you can use the doc-ready stuff with event delegation, but it's simpler to just include your page script at the bottom of the page, like you already do.  :-)
