### ISSUE TITLE
Works in cycle1 but in 2 I get ": opts is undefined" 

### ISSUE THREAD

**Issue by jonas18z** [malsup/cycle2#26]
This code works in cycle1 but not in cycle2. 

$(this).parent('.element').find('.slides').cycle({

```
        fx:      'scrollHorz',

         timeout:  0,

         manualTrump:   false,
```

 next: $(this).parent('.element').find('.next'),

 prev: $(this).parent('.element').find('.prev'),

});

images is in LI elements.

Firebug says 

"TypeError: opts is undefined
[Break On This Error]   

if ( opts.slideCount < 2 ) {"

And with .min

"TypeError: c is undefined
[Break On This Error]   

...(document).on("cycle-destroyed",function(b,c){c._sentinel&&c._sentinel.remove(),..."

**Comment by malsup** [comment]
Can you provide a link?

**Comment by jonas18z** [comment]
Sure,

http://jsfiddle.net/jonas18z/fF49b/

Try to remove cycle2 and change it to http://malsup.github.com/jquery.cycle.all.js in Manage Resources (1) and it will work

Press the blue navigations

**Comment by malsup** [comment]
I don't see any errors when I click those blue boxes.  Nothing happens though because you haven't told C2 what your slides are, so you'd want to add:  

```
slides: '>li',
```

**Comment by jonas18z** [comment]
Aha, but it worked without that parameter in cycle1. Thanks!!

**Comment by malsup** [comment]
Yes, Cycle2 is a different plugin.  It has a different design, different options, different strengths, etc.
