### ISSUE TITLE
Multiple fading cycles falling out of sync

### ISSUE THREAD

**Issue by r-man-MMXIII** [malsup/cycle2#260]
Dear Malsup!

I want these four individual cycles to be a clockwise fading slideshow.  So I set up increasing numbers to the 'data-cycle-timeout'.

http://www.permanentmap.com/test_2013.html

BUT:  After the first cycle the whole event starting to fall out of sync. Eventually it's getting slower and slower. 
My goal is to keep the exact intervals between the slideshows.
Can you help me how to fix this?

**Comment by malsup** [comment]
That URL didn't work.

**Comment by r-man-MMXIII** [comment]
Uh oh! I don't know what's wrong. It seems to be working from here though. :0

If  i set equal timeout numbers the plugin works fine, but otherwise it slows down.
As I noticed the sync problem occurs as fast and clearly as much difference i set between the timeouts.
I put the html code here:

https://gist.github.com/r-man-MMXIII/6195162 

I'm new here on GitHub, let me know, if the code is enough or should i send the whole thing to you somehow.

**Comment by malsup** [comment]
Synchronizing slidehows based on a timeout or delay value will not work, they won't stay synchronized for very long.  You'll need to script it.  

Here's an example:  http://jquery.malsup.com/cycle2/demo/sync.php

**Comment by r-man-MMXIII** [comment]
I'll look into it right away..

EDIT: It works like magic! Thanks for the help, Best of luck to you! ;]

**Comment by r-man-MMXIII** [comment]
I need one more thing to complete the idea: Each time one sequence completed i need to add a timeout. 
The slideshows are four parts of a bigger picture that they are forming, so without some delay 
the viewer can't enjoy the images formed by each sequence. Sorry i didn't clear this for you before.

EDIT: 
It's not scripting, but i found a solution: I put a 5th slideshow in the circle which is not visible, so it's 'cycle-speed' become the delay i needed!  :]
