### ISSUE TITLE
Make two slideshows on the same speed have different speed settings?

### ISSUE THREAD

**Issue by Beckyj01** [malsup/cycle2#261]
I have two cycle2 slideshows here, where I want the top slide to move slower than the bottom one:

http://verilan.right-brain.net/#

Before I synchronized it it seemed like the cycle speed parameters were ignored for each slide show; I had one set to 100 and one to 400.  

So,  I tried synchronizing it and got the results you see when you click on the link. I changed this part of the code:

```
    // trigger the initial transition after 9 second
        setTimeout(transitionNext, 9000);
```

Because I thought I could settle for them both being slower, but this doesn't seem to be effecting anything.

Is there anything I can do to either slow both down or control each slider's speed separately?

**Comment by malsup** [comment]
Use `data-cycle-speed` to control the transition speed.

**Comment by Beckyj01** [comment]
I was using data-cycle-speed but it doesn't work when it's syncing..... I will try again. But I'm really sure it wasn't working.

**Comment by malsup** [comment]
Actually, since you're triggering the transitions manually, try `data-cycle-manual-speed`.

**Comment by Beckyj01** [comment]
That worked! Thanks.
