### ISSUE TITLE
Conflict?

### ISSUE THREAD

**Issue by trinzia** [malsup/cycle2#27]
Hi,
I'm using Cycle1 and have no problems, but when I try to upgrade to Cycle2, all of my images stop loading, even those whihc are not in the slideshow.  

Perhaps I have a conflict with my Tabs and Lightbox scripts?  I am using:
- Dynamic Drive Tabs: http://www.dynamicdrive.com/dynamicindex17/tabcontent.htm
- Highslide: http://highslide.com/

My images are loaded by Jquery so that I could make the large images load after my icons have loaded.  So perhaps my image loading is the conflict?

Here is my page which is working with Cycle1 (but won't with 2), view my code with Firebug, perhaps you can see the issue at a glance?

Click on the 6th icon (decahedron) to see slideshow.
http://instancia.net/portfolio/index.php

Thanks!

**Comment by malsup** [comment]
If you can provide a link to a page that doesn't work then I may be able to help.

**Comment by trinzia** [comment]
Here, sorry, I should have isolated this better before writing... I was tired.  Here is the page isolated from other issues:
http://www.instancia.net/portfolio/cycle2.html

I guess I wouldn't really call this an issue, but... I felt that with large images, I need my smaller UI graphics to load first.  It looked terrible for a good 10 seconds, with the large images loading first.  To control the load order of the images, and also have validated Html (no empty src tags), I wrote a little Jquery to substitute the images after everything else loads.  I suppose that your script is looking for the "img" selector ?

**Comment by malsup** [comment]
Yes, by default it looks for child images of the container, but you can change that to whatever you like with the 'slides' option.  For example:

data-cycle-slides=">span"

For more info:

http://jquery.malsup.com/cycle2/api/#options

**Comment by trinzia** [comment]
I will try it, thanks!
