### ISSUE TITLE
Pager timing: appears to "lag" slide transition

### ISSUE THREAD

**Issue by nator** [malsup/cycle2#270]
The pagers currently adjust their class by binding to cycle-update-view, but to my eyes this makes them appear to lag behind the actual cycle transition. They only update their state after the entire slide has come into view -- not a problem with lightning fast transitions, but troubling even at 200ms.

Thoughts on the best way to make this visual cue sync up?

**Comment by malsup** [comment]
Try setting the 'updateView' option to zero.

```
data-cycle-update-view=0
```

**Comment by nator** [comment]
We tried it as -1, as mentioned in the docs -- no dice. 0 seems to be the answer! Thanks!
