### ISSUE TITLE
CENTER is not working well for images that didnt finish loading before initialization.

### ISSUE THREAD

**Issue by mikila85** [malsup/cycle2#284]
CENTER is not working for images that didnt finish loading before the cycle() is initialized. 
the data-cycle-loader="wait"  is fixing the problem, but the the slider wont show up untill ALL Images has finished loading and that doesnt make sence because i have 20 images and it just taking too long and looks bad on the page.

is there a way for me to manually force it to recalculate the image\s center marging every next\prev ?

**Comment by albell** [comment]
Yes, there is. Look at line 21 of the uncompressed center plugin. Replace that handler with with:

```
opts.container.on( 'cycle-initialized cycle-slide-added cycle-slide-removed cycle-before', function( e, opts, slideOpts, slide ) {
    resize();
});
```

(I've just added in the `cycle-before` event.) This is computationally heavy, recalculating all the margins for each and every slide, on every single transition event (!) but should get you what you want. Off the top of my head, the other option is to listen for the loading of images with <a href="https://github.com/desandro/imagesloaded">imagesloaded</a> and write some fancier custom logic.

Note also my pull request in issue #282, which I needed to get center working right.

As an additional aside, if you're frustrated with long load times, and you're working with large quantities of slides, you might want to look at the <a href="http://jquery.malsup.com/cycle2/demo/lookahead.php">lookahead pattern</a>, which only loads the first two images in markup--great for performance.

**Comment by mikila85** [comment]
Thank you soo much!!! :) you made my day!!
i added the fix you suggested for the <= thanks.

malsup maybe you should consider adding this or a smarter way of recalculating the center when new images are loaded maybe.. this really looks unproffesional when a slider loads the images offside and not centered.

Thanks again :))
