### ISSUE TITLE
Feature: Non-image/HTML slides with progressively loaded images

### ISSUE THREAD

**Issue by shaunmorrison** [malsup/cycle2#29]
Hello

Is there currently a way to have slides containing various HTML to progressively load images contained within the HTML? It would be good not to have to include all the HTML in JSON, but only the images.

Example markup

```
<li>
    <h3>Slide 1</h3>
    <p>Some Text</p>
    <div id="img-1" class="img-wrap"></div>
</li>
<li>
    <h3>Slide 2</h3>
    <p>Some Text</p>
    <div id="img-2" class="img-wrap"></div>
</li>
```

Example JSON

```
[
    { "img-wrap":"#img-1" , "img-src":"images/img-1.jpg" },
    { "img-wrap":"#img-2" , "img-src":"images/img-2.jpg" }
] 
```

Thanks for a great V2 of the cycle plugin.

**Comment by malsup** [comment]
That's not currently supported with the progressive loader but the non-progressive loader can handle images within slides.

**Comment by malsup** [comment]
Check out the "Delimited" example for a way to do this:

http://www.malsup.com/jquery/cycle2/demo/progressive.php#delimited
