### ISSUE TITLE
captions show when string is empty.

### ISSUE THREAD

**Issue by mikila85** [malsup/cycle2#293]
specially with captions2, the captions show when the title and content are empty.

**Comment by mikila85** [comment]
Working JSFIDDLE of the problem:

http://jsfiddle.net/WJJ3v/
(slide number 2)

**Comment by mikila85** [comment]
bump..

**Comment by malsup** [comment]
You can set the caption and/or overlay template to false on slides which have no template metatdata.

http://jsfiddle.net/mbuKL/

**Comment by mikila85** [comment]
ok its working,
no way to auto detect if the string is empty?

thx malsup :)

**Comment by Reggino** [comment]
Thanks guys, excellent, this really helped me.  Maybe this case should be part of the documentation?
