### ISSUE TITLE
Previous / Next controls moving step ?

### ISSUE THREAD

**Issue by Seb33300** [malsup/cycle2#295]
Hello,

I create a "carousel transition" slideshow with the option "carousel-visible" set to 4 and "paused" to true.

So, 4 slides are visible at the same time.

If I click on the prev / next buttons, slides are moving one by one.
What I need is that the 4 visible slides move at the same time to show the 4 next / prev slides.

I didn't found an option to change it. Is it possible ?

An alternative solution could be to group my slides by 4 in one div but i have not the total control of my template.

Thanks

**Comment by malsup** [comment]
That feature is not currently supported by Cycle.

**Comment by Seb33300** [comment]
Same as #106
