### ISSUE TITLE
Pager not working

### ISSUE THREAD

**Issue by jnfsmile** [malsup/cycle2#305]
Instructions say to initiate with local "jquery.cycle2.js".
The repo doesn't have a file named such.
I use "jquery.cycle2.core.js" which is OK, but pager doesn't work.

BTW, when using "http://malsup.github.com/jquery.cycle2.js" pager worked.

**Comment by mikila85** [comment]
Hey, you need to download the production version not the core file. You can find it under the list of files at the begining of the information under "Getting started" title.

**Comment by jnfsmile** [comment]
Thanks
