### ISSUE TITLE
Support for background-size:cover

### ISSUE THREAD

**Issue by dmlogic** [malsup/cycle2#31]
Hi

I've got a project with a custom slideshow that I'd be interested in swapping out for Cycle2.

The slideshow in question uses divs with background images. The divs themselves are 100% width /height and use background-size:cover to get a "full screen" effect.

A quick test suggests cycle2 is not compatible with that. A wrapper containing lots of images works just fine:

```
<div id="gallery"  class="cycle-slideshow auto">
  <img src="im1.jpg">
  <img src="im2.jpg">
  <img src="im3.jpg">
</div>
```

Replace this with background image divs and it doesn't work, the divs are present in generated markup but they're all set to display:none

```
<div id="gallery"  class="cycle-slideshow auto" data-cycle-slides="div">
  <div style="background-image:url(im1.jpg)"></div>
  <div style="background-image:url(im2.jpg)"></div>
  <div style="background-image:url(im3.jpg)"></div>
</div>
```

Am I doing something wrong or is this never going to work?

thanks

**Comment by malsup** [comment]
Seems to work fine for me, or did I misunderstand your question.

http://jquery.malsup.com/cycle2/demo/background.php

**Comment by dmlogic** [comment]
I must have something else going on in my markup that's killing it. I'll start adding bits to your demo until it breaks again!

Thanks for taking the time to confirm it works.
