### ISSUE TITLE
Hide overlay/caption for slides that have none

### ISSUE THREAD

**Issue by malsup** [malsup/cycle2#32]

**Comment by malsup** [comment]
To prevent overlays or captions from being shown for individual slides, set the slide's template to an empty string.  For example, to have no overlay element show for slide 2:

```
<div class="cycle-slideshow">
    <div class="cycle-overlay"></div>
    <img src="http://jquery.malsup.com/cycle2/images/p1.jpg" data-cycle-desc="Sonnenberg Gardens">
    <img src="http://jquery.malsup.com/cycle2/images/p2.jpg" data-cycle-overlay-template="">
    <img src="http://jquery.malsup.com/cycle2/images/p3.jpg" data-cycle-desc="San Franscisco Bay">
    <img src="http://jquery.malsup.com/cycle2/images/p4.jpg" data-cycle-desc="Adirondack State Park">
</div>
```

**Comment by mikila85** [comment]
This isnt working with jquery.cycle2.caption2 animation effects. it just makes it flicker

**Comment by ermushko** [comment]
I know it is too late, but I was in search of solution lately. Nothing was found on internet, so I had to develop it. Hope this will help somebody.
1. Add into common slide template some code like ' style="visibility:{{captionvisible}}" ' to <div> with caption (like in this ex).
2. In slide arguments, add something like ' data-cycle-captionvisible="none" ' or ' data-cycle-buttonshow=" ' just like you set caption text for each slide.

So your data will not only set caption and title as plain text into template, but will set css attribute. Sorry for my English. ;)

**Comment by konekoya** [comment]
A workaround can be found on stackoverflow
http://stackoverflow.com/questions/24662653/how-to-remove-title-or-description-if-empty-in-jquery-cycle2-caption

``` javascript
$('.slideshow').cycle({
    speed: 600,
    manualSpeed: 6000,
}).on('cycle-update-view', function(event, optionHash, slideOptionsHash, currentSlideEl) {
    if (!currentSlideEl.getAttribute('data-cycle-desc') || !currentSlideEl.getAttribute('data-cycle-title')) {
        slideOptionsHash.overlayTemplate = '';
    } else { 
        slideOptionsHash.overlayTemplate = '<div>{{title}}</div><div>{{desc}}</div>';
    }
});
```
