### ISSUE TITLE
centerVert only works after resize-trigger

### ISSUE THREAD

**Issue by bennorz** [malsup/cycle2#35]
When setting up centerVert programatically, I have to use the work-around of triggering resize on the window or the image won't center.
After triggering (or manually resizing the window ofc) everything is fine.
_in combination with autoHeight:'calc' this really is what most other sliders are missing! nice job!_

``` javascript
$(document).ready(function() {
    $('#someslideshow').cycle({
        centerVert: true
    });
    //workaround: 
    $(window).trigger('resize');
});
```

**Comment by malsup** [comment]
Good catch.  Thanks!

**Comment by supermensa** [comment]
Shouldn't this also be triggered when adding slides?
I had a problem with new slides not being centered (Mac, Safari 6.0.2)

**Comment by malsup** [comment]
The center logic is triggered when adding slides.
