### ISSUE TITLE
Allow next and prev as elements to be passed in options.

### ISSUE THREAD

**Issue by bitshadow** [malsup/cycle2#356]
In Cycle2 we can only assign selector to next and prev in options. Is it possible to assign elements like in cycle.

For ex:
next: $('element')
prev: $('element')

Thanks!

**Comment by malsup** [comment]
Yes, that is supported.

**Comment by bitshadow** [comment]
Yup. It is can you put it in the doc as well. Will be helpful to the new users.

Thanks @malsup
