### ISSUE TITLE
Pre-Loading and Responsive images

### ISSUE THREAD

**Issue by matsaukeo** [malsup/cycle2#358]
Hi there 

I'm using background images instead of loading images inline. That way I can take advantage of the orientation media query. I was hoping that I could use "data-cyle-loader="wait"" to wait until the images are loaded but I'm assuming that this is expecting actual inline images and not background images.

Is there a way to do this or could you point me in the right direction? Perhaps the pre-loading should be done outside of this plugin and then pass something in to initiate it?

Cheers
(great plugin BTW)

**Comment by malsup** [comment]
Yeah, cycle can't handle this case for you.  Best to preload by some other means and initialize cycle when the preloading has completed.  You can prevent a slideshow from automatically initializing by adding this attribute:

```
data-cycle-auto-init=false
```

**Comment by matsaukeo** [comment]
got it - thanks!
