### ISSUE TITLE
Feature: Add active class at beginning of transition

### ISSUE THREAD

**Issue by shaunmorrison** [malsup/cycle2#36]
Move the assignation of the active class to when the transition starts. At the moment the active class becomes assigned after the the transition has completed – which can look not so smooth. 

I have a carousel nav that controls a slideshow and when an item in the carousel is clicked I think the user will expect the state to change then not when the transition has completed. 

I looked at the code, but I couldn't seem to switch the order of opts.API.updateView(); without breaking the active class totally.

I hope that makes sense?

Many thanks, 
Shaun

**Comment by malsup** [comment]
You can now control when updateView is invoked.

http://jquery.malsup.com/cycle2/api/#update-view

**Comment by malsup** [comment]
Reverted this feature since it broke a few things.  Need to give this some more thought.

**Comment by malsup** [comment]
Ok, have it working now.

**Comment by shaunmorrison** [comment]
Works perfectly. Thank you for including it!

**Comment by randalldon** [comment]
Hi There,

I'm just picking up on this thread as it's exactly the functionality i'm looking for. Is there an example or you you direct to to how i can achieve this with the API?

Many thanks

**Comment by randalldon** [comment]
Apologies, i've just seen in the documentation how to achieve this.
