### ISSUE TITLE
Customize transition for ONLY first slide

### ISSUE THREAD

**Issue by ghost** [malsup/cycle2#360]
Hi, my carousel is currently using the next/prev and pager options with the scrollHorz effect.

How would i for example using cycle2 have my first slide use a completely customized transition that i could for example build using my own function using a combination of settimeout() and animate() then pass to ONLY my first slide instead of the scrollHorz that the rest are using?

for example: a set of divs that slide out slightly after each other to reveal the second slide..

Thanks!

Sami.

**Comment by malsup** [comment]
You can declare the transition by name on a specific slide to override the slideshow default.  For example, on the C2 homepage, the first slideshow is defined like this:

```
<div class="cycle-slideshow"
    data-cycle-fx='fadeout' 
    data-cycle-auto-height="4:3"
    data-cycle-delay="-1500"
    >
    <img src="http://jquery.malsup.com/cycle2/images/p1.jpg" data-cycle-fx="tileBlind" data-tile-vertical=false class=first>
    <img src="http://jquery.malsup.com/cycle2/images/p2.jpg">
    <img src="http://jquery.malsup.com/cycle2/images/p3.jpg" data-cycle-fx="tileBlind">
    <img src="http://jquery.malsup.com/cycle2/images/p4.jpg">
</div>
```

**Comment by ghost** [comment]
Thanks Pal! One more thing if you will - how can i use before/after on specific slides??

Thanks again!

Sami.

**Comment by malsup** [comment]
You can't have the before/after callbacks invoked for only specific slides.  But the callback is passed enough information to perform conditional logic to drive the behavior you need.
