### ISSUE TITLE
Embedding images in separate individual DIV...

### ISSUE THREAD

**Issue by risuresh** [malsup/cycle2#365]
Hi,

I would like to know if its possible to embed each image in an individual separate DIVs. B'cos I need to include a description of the image as well in the slide.

This is because I want to have some text in it in addition to the image.

Please help me,

thanks,

Isaac

**Comment by malsup** [comment]
http://jquery.malsup.com/cycle2/demo/non-image.php

**Comment by risuresh** [comment]
Thank you Mike.
