### ISSUE TITLE
links inside slides can't be clicked

### ISSUE THREAD

**Issue by mattanimation** [malsup/cycle2#366]
If you set a cycle like this for example, the links for the buttons cannot be clicked,  or even select the text in the slide div why is this? In fact unless you set the data-cycle-slides to  "> a" you cannot click any kind of link nested within the slide div. Or am I missing something.

``````
<div id="banner" class="cycle-slideshow banner" data-cycle-timeout="5500" data-cycle-slides="> div" data-cycle-speed="1200">
                        <div class="banner-container ">
                           <img src="img/someimage.png" alt="..."></img>
                           <div class="banner-text white set-right">
                               <h1>title</h1>
                               <h4>text</h4>
                                <a href="#" target="_blank"><button class="red">click me</button></a>
                            </div>
                       </div>
                       <div class="banner-container ">
                           <img src="img/someimage.png" alt="..."></img>
                           <div class="banner-text white set-right">
                               <h1>title</h1>
                               <h4>text</h4>
                                <a href="#" target="_blank"><button class="red">click me</button></a>
                            </div>
                       </div>

</div>```
``````

**Comment by malsup** [comment]
You must be missing something; probably your css needs to be adjusted.  If you can post a link I could probably help.

**Comment by thinmy** [comment]
Use z-index in your css. I guess that solves

**Comment by mattanimation** [comment]
I tries the z-index and that didn't work, but @malsup was right I was just missing something, I ended up restructuring it slightly and then changed the css a little, and somewhere in between that it worked, sorry I can't say exactly what the change was.

**Comment by manderson725** [comment]
Could you maybe post your new html? I'm having a similar problem and would love to compare structures.
