### ISSUE TITLE
ImageLoader with multiple slideshows

### ISSUE THREAD

**Issue by lenmro** [malsup/cycle2#368]
Hi, I have 4 slideshows on this page, and the image transitions soon get out of sync ...
http://www.95threadingscouts.org.uk/html/index.php
- can anyone tell me how to use the Image Loader feature to wait until all the images from all 4 slideshows have loaded before starting the cycle?
  Thanks

**Comment by malsup** [comment]
You could delay initialization of the slideshows until all images have loaded.  To do so, you would instruct the slideshows not to initialize on the "ready" event by adding the `data-cycle-auto-init=true` attribute.  Then, init the slideshows manually on window load:

```
$(window).load(function() {
    $('.cycle-slideshow').cycle();
});
```

**Comment by lenmro** [comment]
Hi Mike, thanks for replying, that seems to work (when I use auto-init=false), as you can see here ... http://www.95threadingscouts.org.uk/html/index5.php
The only slight problem is that before all the images load, it doesn't even show the first image, which you can see more clearly on this page where I've taken out the window load event  ...  http://www.95threadingscouts.org.uk/html/index4.php
(you also get black bars where the overlays will go)
Is there a way to see the first image in each slideshow immediately, then start the cycle when all the others have loaded?

**Comment by malsup** [comment]
You have a style rule that specifically hides the image:

```
.len_inside {
    display: none;
}
```

**Comment by lenmro** [comment]
Hi Mike, the reason I have that is because I saw it in the FAQ on your website ...http://jquery.malsup.com/cycle2/faq/ where it says "Why do all my images (slides) display briefly when the page loads?" It recommends you have something like:

#slideshow img { display: none }
#slideshow img.first { display: block }

so I have: 

.len_inside { display: none }
.len_inside .first { display: block }

can I remove that now if I'm using window.load?

Thanks

**Comment by malsup** [comment]
That should be:

```
.len_inside.first { display: block }
```

No space before .first.
