### ISSUE TITLE
Multiple "prev/next" buttons 

### ISSUE THREAD

**Issue by paulsende** [malsup/cycle2#375]
Hi, I hope you can help me with this problem.

Here is the project I working on: http://paulsende.com.ar/mical/web5/galeria.html

The idea is you can prev/next pictures both from arrows (left below) or hitting the image directly (left side, prev, right side, next), but from some reason, it works just for one pair of prev/next buttons (always the first ones in the code)... So now arrows are not working...

Does anyone knows what's happening? 

Thank you very much!

Paul

**Comment by malsup** [comment]
You can't have more than one element with the same id.  Ids must be unique.  You should use classes instead of ids.

**Comment by paulsende** [comment]
Thank you malsup, I'm trying to fix it using classes instead of ids but it doesn't work... I suppose I have to change something on jquery.cycle2.js file, but I really don't know what! Thank's again man.

**Comment by paulsende** [comment]
Ok I fixed it! Just changed  data-cycle-prev="#prev" to  data-cycle-prev=".prev".
