### ISSUE TITLE
Pager counting as a cycle-slides element

### ISSUE THREAD

**Issue by davidsword** [malsup/cycle2#382]
when you set your slide element to DIV via `cycle-slides='> div'` 
if you have `<div class='cycle-pager'>` inside the slideshow for pager, it turns the pager into a slide not a slideshow pager (obviously, because it's a `div`). 

But, shouldn't there be an exception that any `.cycle-pager` class on ANY type of element can NEVER be a slide itself? I myself have messed up on this half a dozen times already. One would think when the `pager='>.cycle-pager'` has been set, it would exempt it from becoming a slide regardless of the element type.

**Comment by malsup** [comment]
You are specifically providing the selector string for the slides, therefore you have complete control over what gets selected.  I would recommend either adding a class to your slides and selecting by that, or excluding the pager in your selector string.

1)  cycle-slides="> div.slide"
2)  cycle-slides="> div:not(.cycle-pager)"

**Comment by davidsword** [comment]
Makes sense.

PS. great plugin, use it on 100% of my sites for as many years as I've been developing. Thank you so much for your work!

**Comment by malsup** [comment]
Nice to hear.  Thanks!

Cheers!
