### ISSUE TITLE
Chrome can't find jquery.cycle2.js.map

### ISSUE THREAD

**Issue by oskrabanek** [malsup/cycle2#384]
Can I download somewhere jquery.cycle2.js.map? For jQuery the map file is provided on their web, but I can't find jquery.cycle2.js.map anywhere.

**Comment by malsup** [comment]
http://malsup.github.io/min/jquery.cycle2.js.map

**Comment by hanneskaeufler** [comment]
Whats this anyway? Why does Chrome complain here?

EDIT: Found out by a simple Google ... :-)
See e.g. http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/ if interested

**Comment by treysea** [comment]
thanks for this!

**Comment by eberkund** [comment]
Is this as intended? Why can't this file be combined with the main .js file?
