### ISSUE TITLE
Images are all stacked vertical with even the most basic slideshow (Its broken)

### ISSUE THREAD

**Issue by SpeakDesign** [malsup/cycle2#389]
Hi,
I have tried to use the most basic Cycle 2 slide show (copy and pasted from website) and it is just stacking the images vertically. I checked to make sure the Jquery and Cycle2.js are linked and they are.I have a bootstrap base and made a new blank bootstrap doc to test it out and it worked fine.  I am wondering if something is over riding Cycle2. I am a novice so odds are this is user error.

My site is speak-design.com

username: tspeak
pass: test123

I have put the gallery at the top of the page.

**Comment by malsup** [comment]
You have a javascript error on that page.

```
Uncaught ReferenceError: Modernizr is not defined
```
