### ISSUE TITLE
auto-height=calc broken

### ISSUE THREAD

**Issue by sebastianschmid** [malsup/cycle2#39]
I have a slidehow where the images (coming out of wordpress) are limited in height, rather than width.
On mobile devices, the usual max-width & height = auto approach is used, and so I need to set height for sentinel by using auto-height = calc.

However, the picture picked seems not right. 

``` php
        if ( autoHeight === 'calc' ) {
            // calculate tallest slide index
            opts.slides.each(function(i) {
                var h = $(this).height();
                if ( h > max ) {
                    max = h;
                    autoHeight = i;
                }
            });
        }
```

It's clear to see that you only compare for height, and not for ratio.

I'm working on a solution and will post an update.

**Comment by sebastianschmid** [comment]
pew. seems to me that the whole prodecure is flawed. A "debugger;" call reveals, that $(this), the slide, has zero height all of the time.

for me, this works:

``` php
        if ( autoHeight === 'calc' ) {
            // calculate tallest slide index
            opts.slides.each(function(i) {
                // debugger;
                // this one didn't work
                // var ratio = $(this).height() / $(this).width();
                var ratio = $('img',this).attr('height') / $('img',this).attr('width');
                opts.API.log('image '+i+': ratio='+ratio+' | max='+max);
                if ( ratio > max ) {
                    max = ratio;
                    autoHeight = i;
                }
            });
        }
```

since I put the height and width of each image in the according attribute. It's neither fully tested, nor a complete solution.

Update:
See live at http://www.dietersteinbach.com/
Resize window to be about 400px wide (minimum possible width in chrome) to see the mobile stylesheet.

**Comment by malsup** [comment]
Yeah, that's pretty tricky if you have variable sized images set to 'auto' height.  Another approach would be to delay the style initialization until after cycle has a chance to calculate the correct sentinel:

```
.cycle-slide img { display: block }


$('.slideshow').on('post-intialize', function() {
    $('.cycle-slide img').css({ maxWidth: '100%', height: 'auto' });
});
```
