### ISSUE TITLE
slidecount error when removing Cycle2

### ISSUE THREAD

**Issue by Darknior** [malsup/cycle2#391]
Hi,

For my part i don't really have problem with this perfect plugin, all is working perfect.
I read the doc a lot ;)

But, i found one little bug on this plugin. I make a site in Ajax, i put the Cycle2 on home page, and when i change page, i don't relod the full page, i only remove the central DIV with Cycle2 slideshow and replace it by an other one without Cycle2 inside.
At this moment Cycle2 can't found the slideshow DIV and crash with : 

Uncaught TypeError: Cannot read property 'slideCount' of undefined 

I don't found how to test in the DOM if a Cycle2 instance is running ?
Or maybe it is possible to change Cycle2 engine to stop alone when the DIV gone ...
Because i don't really want to test each time i change page if the Cycle2 instance is already running for only one page with it!

Can you halp me please ?
This eror is not important and don't crash the site, but it is not perfect :package:p

**Comment by malsup** [comment]
Before removing the div, destroy the slideshow:

```
$('.cycle-slideshow').cycle('destroy');
```

Then, after inserting the new content, initialize the slideshow (if there is one):

```
$('.cycle-slideshow').cycle();
```

**Comment by Darknior** [comment]
Thanks, but i know it lol
I'm not a stupid coder and i have read the doc :p 

My site is full AJAX ! I don't and can't know when the DIV is removed.
The CMS can do it many time when it want ... i can't say it to destroy Cycle2 instance!
Or i must make MANY tests and it will use some browser power ... and i don't want it, i prefer always use less power of the user computer.

I would like that Cycle2, when it try to make a cycle, test the DIV himself, and if the div is gone, it not crash but destroy himself. With a console.log if you want ...

Is it possible for you easilie ?
It is the best solution and for you too can prevent some stupid crash ...
