### ISSUE TITLE
Issue with swipe gestures in iOS6

### ISSUE THREAD

**Issue by davidrhansen** [malsup/cycle2#4]
When using swipe gestures for next/prev navigation, if you touch into the slideshow and make an "L" gesture, by either first dragging down and left, or up and right, 2 issues occur:
1. animations stop working, transitions between slides become instantaneous
2. if a pager is present, the active pager item becomes out of sync with current slide

This can also be triggered with 2 separate gestures. If you first swipe down (to scroll), and quickly swipe left or right within the slideshow node before the original vertical scroll animation has finished, you see the same results. 

Using Mobile Safari in iOS6, tested on iPad and iPhone. The first issue above can be seen on http://jquery.malsup.com/cycle2/demo/swipe.php

**Comment by davidrhansen** [comment]
Upon further testing, it appears this issue is isolated to iOS6. I am unable to reproduce in Android or iOS5 devices.

**Comment by malsup** [comment]
Yeah, I can't reproduce on Android/Chrome.

**Comment by owenhoskins** [comment]
This bug also occurs when using jQuery Mobile for Swipe support. Any idea which side of the equation is responsible for this behavior?

**Comment by malsup** [comment]
Unfortunately I don't have an iOS6 device to test with.

**Comment by davidrhansen** [comment]
A bit more info discovered while using Safari's dev tools in XCode's iOS Simulator:

If I swipe left, console logs 'cycle-next' and advances slider 1 step (correct behavior)

If I swipe up, then left before the vertical scroll animation completes, console logs 'cycle-next' but does not advance my slider or pager. All subsequent swipes or pager clicks are bugged until I refresh the page.

**Edit** -- correction -- originally reported that a horizontal swipe combined with a vertical swipe logged an opposite action (cycle-next vs cycle-prev) than a standalone horizontal swipe of the same direction. this is not the case, they both log the correct action, the difference being the horizontal / vertical combined swipe doesn't actually perform the advancement.

**Comment by owenhoskins** [comment]
Cycle1 + jSwipe is still functioning as expected on iOS6, so I am considering reverting back to Cycle1... although I'd prefer not to.

EDIT: Cycle 1 + Swipe plugin produces the same glitch when iOS6 registers a scroll swipe while Cycle is animating.

@malsup, Is this something that you intend to look (somehow) in the near future or would you recommend reverting?

best,
Owen

**Comment by malsup** [comment]
Yes, I plan to look into this.  But in the meantime, doesn't jswipe work with cycle2?

**Comment by owenhoskins** [comment]
@malsup, Just tried the Jquery Touchwipe plugin (mixed up the names, didn't mean Jswipe), and it produces the same glitch. I then reverted to Cycle1 + Touchwipe, and I am getting the same exact glitch, unfortunately...

What it seems to be is that if the iOS6 registers a vertical swipe as a scroll while Cycle is still animating, it breaks.

**Comment by newelement** [comment]
I can confirm this as well on iOS6 at least.

**Comment by malsup** [comment]
I don't have an iOS device to test on so can someone please test this new impl as a replacement for my current swipe plugin?

http://jquery.malsup.com/cycle2/jquery.cycle2.zwipe.js

**Comment by newelement** [comment]
I updated the above file and swipe does not seem to work anymore.

**Comment by malsup** [comment]
Here's a test page that uses a different swipe impl.  Works on Android, how about iOS?

http://malsup.com/jquery/cycle2/demo/swipe2.php

**Comment by newelement** [comment]
That page is working for me on iOS6 / iPhone 5

**Comment by owenhoskins** [comment]
Just tested it on iOS6 / iPhone 4s and its breaking the same way... I had also tested jQuery mobile and Touchwipe swipe implementations as well,  I am afraid it is something mor core to cycle+iOS6, as I also discovered this glitch with cycle1.

**Comment by davidrhansen** [comment]
Tested here on iOS6 iPad 2 & iPhone 4s, the example at http://malsup.com/jquery/cycle2/demo/swipe2.php still breaks the same way

**Comment by malsup** [comment]
This script fixes the problem if you include it on your page (confirmed by testing).

https://gist.github.com/3798925

Found it via comments on this ticket:  http://bugs.jquery.com/ticket/12620

**Comment by malsup** [comment]
Added note to swipe demo page:  http://jquery.malsup.com/cycle2/demo/swipe.php

**Comment by sarathrajan** [comment]
Hi.. I have added the fix.js in my header and issue seems to be fixed. But my images are inside a link (<a></a>), while clicking the image, its not redirecting. Just showing the loading icon and nothing happens after that. Please need help on this :(

**Comment by dejami-jphillips** [comment]
To make images wrapped in links,   you make the > a  the slide, not the image.  
See 'Anchors' section on this page: http://jquery.malsup.com/cycle2/demo/non-image.php
