### ISSUE TITLE
swipe gestures

### ISSUE THREAD

**Issue by sebastianschmid** [malsup/cycle2#40]
http://www.dietersteinbach.com/kunden/faces-in-studio/

I've sometimes had a bug now, which can be more or less reproduced:
- open http://www.dietersteinbach.com/kunden/faces-in-studio/ on iPhone 4S (in my case)
- swipe wildly left and right

After a while, two images are visible at the same time: http://imgur.com/tnMju
furthermore, the controls (next / prev) are one step behind.

Just an idea - maybe swiping too fast causes the issue? Like if you start the next swipe even before the previous one has properly executed the slide transition?

**Comment by malsup** [comment]
Is this iOS6?  Did you read the note at the top of this page:

http://jquery.malsup.com/cycle2/demo/swipe.php
