### ISSUE TITLE
Firefox shifts entire slideshow.

### ISSUE THREAD

**Issue by Johns3n** [malsup/cycle2#403]
Hi Malsup!

First off thanks for a awesome plugin, that hasn't given much headache until now unfortunately :(

I've created a slide which can be seen on the top of the page here:

And it works flawlessly in chrome however in Firefox, when it slides to the next slide, it shifts the entire slideshow to the side, i've looked every where in my css and html and setting for cycle2 and i can't seem to find any problems, which i am now turning into this issue for cycle2 in firefox.

**Comment by bskarger** [comment]
Hello - I'm now experiencing a shift during fade transition - but only in Firefox. You see the slight (1px or so) shift right as the transition fires:

Cycle images are top center of content area:
http://www.kathleenernst.com/book_heritage_darkness.php

As far as I know, this is relatively "new" behavior, and the client noticed it!

**Comment by netnothing** [comment]
So I think this has to do with jQuery and Firefox.  I'm only seeing this on OS X.  But I did come across this post:

http://forums.mozillazine.org/viewtopic.php?f=9&t=2439275

I have the issue on other jQuery fades.  The solution posted there of giving the image a box shadow:

box-shadow: #000 0em 0em 0em;

Has worked for me.

-Kevin
