### ISSUE TITLE
Add buttons & links to Slideshow

### ISSUE THREAD

**Issue by j8kerussell** [malsup/cycle2#410]
Hi,
I would love to be able to add a "Read More" button below the title and description of my slideshow AND a link to the image itself (Button/Image on each slide gets their own unique link). 

I went through and put together some code, but it's not correct and I haven't been able to figure out how to add unique links for the button. Here's the fiddle: http://jsfiddle.net/p3Tm3/4/

The yellow box is where I was imagining Read More would be. Does anyone have any thoughts on how to do this? Thank you.

**Comment by thinmy** [comment]
Hi,

you can use a div instead of img and captions. 

http://jquery.malsup.com/cycle2/demo/non-image.php

a quick example
http://jsfiddle.net/p3Tm3/4/

**Comment by j8kerussell** [comment]
Hey, 
This is great, thanks! The fiddle example you sent along looks like the one I sent in the original post. Was there another one you meant to send?

**Comment by thinmy** [comment]
Sorry, 
I paste a wrong fiddle

**Comment by j8kerussell** [comment]
No problem. Were you planning to resend it? I don't see it in your previous comment.

**Comment by thinmy** [comment]
Here.

http://jsfiddle.net/p3Tm3/6/

just a sample

**Comment by j8kerussell** [comment]
This is great, thank you! How does one style the button? I see a class="button" but I don't see any CSS to style it.

**Comment by thinmy** [comment]
you need to create your own class, you can change this class if you have one to style the button.

like

.button {
padding: 1em;
background-color: #ff0000;
font-weight: bold;
}

.button:hover {
background-color: #00ff00;
}

**Comment by j8kerussell** [comment]
It works, thank you!
