### ISSUE TITLE
Play/Pause

### ISSUE THREAD

**Issue by tdprout** [malsup/cycle2#411]
Love this script!  I would like to get an functional toggle Play/Pause button, it is my understanding that Jquery no longer supports this feature.  How can I still get this functionality?

**Comment by FlashJunior** [comment]
Checkout the api: http://jquery.malsup.com/cycle2/api/

there are comments "pause / resume" so you can build it.
you can test it here: http://jquery.malsup.com/cycle2/demo/command.php

**Comment by malsup** [comment]
C2 doesn't have a 'toggle' command but you could create a toggle button easily enough that sends either a 'pause' or 'resume' command to the slideshow.  Or you could use declarative buttons like this:

```
<button data-cycle-cmd="pause" data-cycle-context="#mySlideshow">Pause</button>
<button data-cycle-cmd="resume" data-cycle-context="#mySlideshow">Resume</button>
```
