### ISSUE TITLE
unwanted cycle-update-view execution

### ISSUE THREAD

**Issue by mattanimation** [malsup/cycle2#412]
I have a cycle gallery(c) nested inside of an instance of cycle(b) that is nested in another instance of cycle(a). I added a cycle-update-view event onto "a" in the hopes that whenever "a" transitions I can set some other variables. The unwanted effect is that whenever the children "c" or "b" change or transition, it fires that update event that is on the parent. Is there a way to curtail this unwanted effect? Is there a way to keep the parent event from firing when the children have changed?

**Comment by malsup** [comment]
This is just normal event bubbling.   Check the event's target to filter as needed.
