### ISSUE TITLE
Centering Plugin, run resize on window load

### ISSUE THREAD

**Issue by petertwise** [malsup/cycle2#414]
I was having lots of trouble with responsive images and the centering plugin.  Particularly a problem with webkit browsers.  After a lot of failed solutions this simple one worked: I added the on window load event to the list of events that causes a resize calculation.

Line 17 of jquery.cycle2.center.js:

```
$(window).on( 'resize orientationchange load', resize );
```

**Comment by malsup** [comment]
Nice.  I like it.  Thanks.
