### ISSUE TITLE
Change #419 breaks slideshows using recommended FOUC CSS

### ISSUE THREAD

**Issue by andymb** [malsup/cycle2#423]
http://jquery.malsup.com/cycle2/faq/ suggests using CSS to prevent FOUC on slides by setting them to 'display: none;' before Cycle2 fires.

Change #419 changes the slide hide/show mechanism to use 'visibility' instead and so slides hidden to prevent FOUC are never displayed.

**Comment by andymb** [comment]
I should add that the right fix for anyone preventing FOUC in this way is to change their CSS, either to 

1 - put 'display: block' on the current slide,

or, better as it goes with the rationale for Malsup's code change #419,

2 - change your FOUC code to use visibility instead.

Hope this helps anyone waking up to 'broken' slideshows.

**Comment by malsup** [comment]
Thanks for catching and reporting this.
