### ISSUE TITLE
Newbie question...don't get logic of events

### ISSUE THREAD

**Issue by creamofthecrop** [malsup/cycle2#425]
I just want to get the information which slide is currently active and use that information to trigger the background color of a button outside of cycle2. For a start - this is what I'm trying:

$('.cycle-slideshow').on( 'cycle-before', function( event, currSlide) {
            var x = currSlide;
            console.log('Slidenr.: ' + x);
});

Console tells me: Slidenr.: [object Object]

Same result with

$('.cycle-slideshow').on( 'cycle-before', function(event, optionHash, outgoingSlideEl, incomingSlideEl, forwardFlag) {
    var x = optionHash;
    console.log('Slidenr.: ' + x);
});

If I had the actual number I could trigger the corresponding button.

I just don't get it...

**Comment by malsup** [comment]
```
optionHash.currSlide
```

http://jquery.malsup.com/cycle2/api/#misc

**Comment by creamofthecrop** [comment]
Great! Thanks a lot
