### ISSUE TITLE
cycle2 does not trigger cycle-finished event

### ISSUE THREAD

**Issue by peterbelsky** [malsup/cycle2#428]
having trouble getting cycle-finished to trigger. does anyone see what is wrong with this

http://jsfiddle.net/aQe8X/

**Comment by malsup** [comment]
cycle-finished is meant to be used with the "loop" option:

http://jquery.malsup.com/cycle2/api/#events

**Comment by FlashJunior** [comment]
duplicated: https://github.com/malsup/cycle2/issues/427
