### ISSUE TITLE
caption2 overlay not working

### ISSUE THREAD

**Issue by arnoldbird** [malsup/cycle2#429]
I am not getting the overlay effect when I try to follow the first example at http://jquery.malsup.com/cycle2/demo/caption2.php

The caption is appearing below the image, rather than overlaid on top of the image.  Here is my HTML:  http://pastebin.com/BQnNsnkf

I have confirmed that the caption2 script is referenced in the HTML document.

Thank you

**Comment by malsup** [comment]
Please link to a jsfiddle or simple test page that shows the issue in action.  Thanks.

**Comment by arnoldbird** [comment]
I just needed to add the reference to your CSS: http://jquery.malsup.com/cycle2/demo/demo-slideshow.css

Once I reference your CSS, the overlays work.
