### ISSUE TITLE
How I get CurrentSlide and MaxSlide

### ISSUE THREAD

**Issue by rpontes** [malsup/cycle2#43]
Hi, I need use currentslide and maxslide in my javascript, but I don't know how I do this.

Thanks.

**Comment by malsup** [comment]
In what javascript?  In a cycle event handler?  Which event?  Here's a list of the events:

http://jquery.malsup.com/cycle2/api/#events

In the callbacks, `optionHash` gives you access to `currSlide` and `slideCount` properties.

**Comment by rpontes** [comment]
HI, thanks.

**Comment by svilenkov** [comment]
Why aren't public get methods that allow you to query such status variables just by using the plugin instance? For example: `$('#cycle').('currSlide');`

**Comment by FlashJunior** [comment]
@keeperhood you can find all slideshow options and stats in `.data("cycle.opts")`

Example:
$("#slidehsow").data("cycle.opts").currSlide
$("#slidehsow").data("cycle.opts").slideCount

PS: you can use firebug with [firequery](http://firequery.binaryage.com/) Extention to see all :-)

**Comment by svilenkov** [comment]
Great, thanks, I've completely missed that, been looking everywhere
