### ISSUE TITLE
data-cycle-pause-on-hover issue

### ISSUE THREAD

**Issue by discodavey** [malsup/cycle2#432]
When I load the page and the mouse is over the slideshow and then I move the mouse away, nothing happens. The slideshow works properly if the mouse is away from the slideshow on page load and pauses on mouse over.

Any ideas or is this a bug?

Thanks

**Comment by discodavey** [comment]
Found the issue. I was using an older version of the js. Updated to the new one and all is ok.

**Comment by malsup** [comment]
Thanks for the update.
