### ISSUE TITLE
keyboard Navigation

### ISSUE THREAD

**Issue by f1shman** [malsup/cycle2#44]
hy,
would it be possible to add keyboard navigation to the cycle plugin?
So you can switch through the i mages by using the keyboard keys.

In my last project, i added it manually:

``` javascript
//gallery keyboard evetns
    $(document.documentElement).keyup(function (event) {
      if (event.keyCode == 37){
        $('.slider').cycle('prev');
      }else if (event.keyCode == 39){
        $('.slider').cycle('next')
      }
    });
```

**Comment by malsup** [comment]
I don't think there is a good way to add this behavior generically.  For example, what if there are multiple slideshows on the page.  I'd recommend that you just include the snippet that you already have.
