### ISSUE TITLE
Youtube - cant make video with the size of parent div

### ISSUE THREAD

**Issue by iDavemay** [malsup/cycle2#441]
Hey, so I'm converting a client's one div w/ a youtube embed into a slider with the Cycle2 youtube plugin. 

The video's width is 820px X 335px but when I embed the cycle2 code it only allows it to be the auto size (about 300px x 150px)

I have auto-height but not sure what else to do. Thank you.
![youtubecycle2](https://f.cloud.github.com/assets/5295427/2173948/2d4aced6-95a9-11e3-9644-d9ed913ec2cb.jpg)

**Comment by iDavemay** [comment]
Solved this thank you.

**Comment by alfacommunication-alessandro** [comment]
Can you share the solution, please?

**Comment by marcelo2605** [comment]
And the solution is...?

**Comment by ryanswedal** [comment]
I'm pretty sure that this CSS is the solution... 

.cycle-slideshow > div { width: 100%; height: 100% }
iframe,object,embed { width: 100%; height: 100% }

**Comment by axelcaballero** [comment]
Thanks for sharing the solution!

**Comment by nickfmc** [comment]
adding .cycle-slideshow > div { width: 100%; height: 100% } could throw some people off if their slider items are divs.  you can replace that one with just .cycle-youtube { width: 100%; height: 100%; }

**Comment by daniellelecomte** [comment]
Still can't resolve this issue on my end. Does anyone have a solution that actually works? Thanks! :-)
