### ISSUE TITLE
Image anchor tags break the captions

### ISSUE THREAD

**Issue by felix822** [malsup/cycle2#451]
When I try to wrap my images with a tags to create links, it seems that the captions break and I think the transition does as well. Please se my jsfiddle for an example - http://jsfiddle.net/felix822/3PW9B/2/

Thanks for any input!

**Comment by malsup** [comment]
Your title and desc attributes need to go on the slides.

http://jsfiddle.net/3PW9B/4/

**Comment by felix822** [comment]
Thanks that worked!!
