### ISSUE TITLE
Cycle2 carousel click on thumbnail to show content

### ISSUE THREAD

**Issue by sebastiangraz** [malsup/cycle2#452]
http://jsfiddle.net/r29A9/4/ (click the next and prev divs below to see the functionality)

Not really a bug but I have a question. I am using Cycle2 to slide some content and currently it's working fine the way I want it (check fiddle above). But I also want to be able to click on each thumbnail (round cyan/blue circle) and go to that specific content, once clicked.

I discovered this snipped below on this page: http://jquery.malsup.com/cycle2/demo/caro-pager.php which I want to sort of copy the functionality from. And I have tried to integrate it with my current setup but to no avail.

var slideshows = $('.cycle-slideshow').on('cycle-next cycle-prev', function(e, opts) {
// advance the other slideshow
slideshows.not(this).cycle('goto', opts.currSlide);
});

$('#cycle-2 .cycle-slide').click(function(){
var index = $('#cycle-2').data('cycle.API').getSlideIndex(this);
slideshows.cycle('goto', index);
});
Do you guys have any ideas? Thank you!

**Comment by freestyleinternet** [comment]
Give this extra line a try (above you code you already have):
var slideshows = $('.cycle-slideshow').on('cycle-next cycle-prev', function(e, opts) {
    slideshows.not(this).cycle('goto', opts.currSlide);
});

**Comment by sebastiangraz** [comment]
Thank you freestyle for the comment. I should have closed the topic but I forgot when I solved it through stackoverflow a couple of weeks ago. For others who are curious, the code you provided does work and does solve the problem. Thank you!
