### ISSUE TITLE
add image link or link for caption not work

### ISSUE THREAD

**Issue by Jawanet** [malsup/cycle2#453]
Please help me how to be able to add a link to a picture and caption stidak error...!!!

I say thank you a lot if you are willing to help....

my site http://banyudadi.com

<pre>
&lt;div class="cycle-slideshow" 
    data-cycle-fx=scrollHorz
    data-cycle-timeout=3000
    data-cycle-caption-plugin=caption2
    data-cycle-overlay-fx-out="slideUp"
    data-cycle-overlay-fx-in="slideDown"
    >
    &lt;div class="cycle-overlay">&lt;/div>

    &lt;img src="<?= $imagePath ?>/images/p1.jpg" data-cycle-title="Spring" data-cycle-desc="Sonnenberg Gardens">
   &lt;img src="<?= $imagePath ?>/images/p2.jpg" data-cycle-title="Redwoods" data-cycle-desc="Muir Woods National Monument">
    &lt;img src="<?= $imagePath ?>/images/p3.jpg" data-cycle-title="Angel Island" data-cycle-desc="San Franscisco Bay">
    &lt;img src="<?= $imagePath ?>/images/p4.jpg" data-cycle-title="Raquette Lake" data-cycle-desc="Adirondack State Park">
&lt;/div>
</pre>

i use not work

<pre>
&lt;div class="cycle-slideshow" 
    data-cycle-fx=scrollHorz
    data-cycle-timeout=3000
    data-cycle-caption-plugin=caption2
    data-cycle-overlay-fx-out="slideUp"
    data-cycle-overlay-fx-in="slideDown"
    >
    &lt;div class="cycle-overlay">&lt;/div>

     &lt;a href="http://">
&lt;img src="<?= $imagePath ?>/images/p1.jpg" data-cycle-title="Spring" data-cycle-desc="Sonnenberg Gardens">
  &lt;/a>
&lt;/div>
</pre>

Please please please help me, me love cycle2

**Comment by Jawanet** [comment]
Oh not solution for me hix,
The setting is very complicated.
non-image not work with me

**Comment by malsup** [comment]
If you're going to use anchors as the slide elements then you need to tell cycle that:

```
data-cycle-slides=">a"
```

And then you need to move your title and desc attributes from the images to the anchors:

```
<a href="http://blah" data-cycle-title="my pic" data-cycle desc="pic desc">
    <img src="/images/p1.jpg" >
</a>
```

Putting that all together you would have:

```
<div class="cycle-slideshow" 
    data-cycle-slides=">a"
    data-cycle-fx=scrollHorz
    data-cycle-timeout=3000
    data-cycle-caption-plugin=caption2
    data-cycle-overlay-fx-out=slideUp
    data-cycle-overlay-fx-in=slideDown
    >
    <div class="cycle-overlay"></div>
    <a href="http://blah1" data-cycle-title="pic1" data-cycle desc="pic1 desc">
        <img src="images/p1.jpg" >
    </a>
    <a href="http://blah2" data-cycle-title="pic2" data-cycle desc="pic2 desc">
        <img src="images/p2.jpg" >
    </a>
</div>    
```
