### ISSUE TITLE
No progress bar

### ISSUE THREAD

**Issue by yroc** [malsup/cycle2#454]
I copied and pasted the progressbar code (from http://jquery.malsup.com/cycle2/demo/progress.php) into the head of my page.

Then I added the element

```
<div id="progress"></div>
```

to the cycle-slideshow div.

And finally I copied and pasted the CSS code

```
#progress {
  position: absolute;
  bottom: 0;
  height: 6px;
  width: 0px;
  background: #c00;
  z-index: 500;
}
```

to my stylesheet.

I thought this would be enough to get a progress bar, but there's nothing. Is there something else I'm missing? Otherwise I think it's a bug.

**Comment by malsup** [comment]
What's a bug?

Can you post a link to your page?

**Comment by yroc** [comment]
Sure: pianowithlori.com

**Comment by malsup** [comment]
Put that script block at the bottom of your page, not in the head.  You're trying to access elements that don't exist in the DOM yet.

**Comment by yroc** [comment]
Ah, so it's not a bug; just my lack of understanding of how JS works!
Thanks very much (for the help and for your slideshow plugin).
