### ISSUE TITLE
None of the "initialization" events are called.

### ISSUE THREAD

**Issue by dog5tar** [malsup/cycle2#46]
Hi,

I tried to listen to 'cycle-initialized' (and then to any of initialization event) but they aren't called.

Events like cycle-resumed, cycle-before, cycle-update-view etc. are working.
No luck with cycle-initialized or any of the initialization events.

I'm using this URL for testing.
http://malsup.github.com/jquery.cycle2.js

**Comment by malsup** [comment]
You're probably binding your listeners after the events have already fired.

**Comment by dog5tar** [comment]
Yes. You are right. Thanks.

P.S. I would suggest to update API docs and put an example regarding this :)
