### ISSUE TITLE
naming issues: .cycle() vs .cycle2()

### ISSUE THREAD

**Issue by romgen** [malsup/cycle2#463]
The problem is that there is already a plugin called "cycle" which is used by several other plugins and themes: "Cycle" (used by e.g. Maximage).

The problem is then I want to use cycle2, that they both use the same function name "cycle".

Cycle2 function name should be renamed "cycle2" to avoid name collision issues.

**Comment by malsup** [comment]
The name choice is intentional.  I want to discourage both plugins being used on the same page because that results in a footprint of over 50kb just for slideshows.  That, imo, is significant overkill.
