### ISSUE TITLE
Duplicate slide element

### ISSUE THREAD

**Issue by justinmz** [malsup/cycle2#467]
I'm using Cycle in conjunction with Magnific popup (https://github.com/dimsemenov/Magnific-Popup) but there's a duplicate item in the gallery. I've set data-cycle-allow-wrap='false' and also tried adding data-cycle-loop=1 to stop this but I still get the duplicate first slide.

Any ideas?

**Comment by tie624** [comment]
It's probably the sentinel slide. Try this:
$('.cycle-slide').not('.cycle-sentinel').magnificPopup({
  type: 'image',
  gallery:{
    enabled:true
  }
});

**Comment by justinmz** [comment]
Just in case anyone else has a similar problem.
It was the sentinel but the solution I used was to add data-cycle-auto-height="780:490" which was my desktop image size but gets translated as a ratio so it still resizes for responsive layouts.
This is the alternative for the sentinel slide, you can view more detail here http://jquery.malsup.com/cycle2/demo/autoheight.php

**Comment by tnk00** [comment]
Same scenario cycle + magnific-popup, thanks for posting!
