### ISSUE TITLE
Validating slide before transition

### ISSUE THREAD

**Issue by janhartmann** [malsup/cycle2#468]
I was wondering if there is something wrong with how the cycle-before is trigged.

Story:
I wish to validate each slide in the slideshow, when I click a next button. For that I fire the cycle-before event and validate the slide (in my example some form elements), but it would be great, if you from this event could return false to trigger if the slide should advance to the next. 

Calling .cycle('stop') or .cycle('pause') from this event seems to not make the slideshow stay on the slide triggering the event.

Setup:

``` html
<div id="questions" class="cycle-slideshow"
         data-allow-wrap="false"
         data-cycle-caption="#question-progress"
         data-cycle-caption-template="Question {{slideNum}} of {{slideCount}}"
         data-cycle-slides="div.question"
         data-cycle-fx="scrollHorz"
         data-cycle-timeout="0"
         data-cycle-next="#next-question">

         <div class="question"> ... </div>
         <div class="question"> ... </div>
         <div class="question"> ... </div>

</div>

<a id="next-question" href="#">Next question</a>
```

**Comment by noraheuer** [comment]
I noticed that too. Pausing the slideshow from within cycle-before will still transition the current slide out rather than stop before the transition.

**Comment by tie624** [comment]
You can probably do a workaround for this.
Instead of hooking up the anchor to data-cycle-next, bind the click event to a method that does the validation, then call .cycle('next') if the validation succeeds.

**Comment by janhartmann** [comment]
This is a good workaround, I'll do that - thanks!
