### ISSUE TITLE
Transitions  "after"

### ISSUE THREAD

**Issue by munkex** [malsup/cycle2#47]
Hey.
Im wondering if i understand your documentation wrong.

i got the following script: 

$('.slider').cycle({
     after: function(){
            alert('hmm');
     },
     swipe: true,
     speed: 1000,
     timeout: 1000,
     overlay: '.slide_overlay',
     overlayTemplate: '<div><div class="slide_overlay_inner"><div>{{title}} {{alt}}</div></div><a href="{{cycleRel}}" class="' + classtouse + '"></a></div>',
     log: false
});

and following html:

http://jsfiddle.net/8gYTX/

It all works perfect exepct for the part where im trying to use after:

Nomatter what i do i cant get it to work, what am i doing wrong here?

i even tryed before and it aint working either wont run the alert.

Also i got a isecond question, im wondering if theres a easier way to detect if the {{title}} or {{cycleRel}}
than having to use the after:

Reason is i need it to hide the "slide_overlay_inner" if either {{title}} or {{cycleRel}} is empty

Hope i made myself clear on what i needed and hope that your able to help out.

Greets
Martin

**Comment by malsup** [comment]
Right, there is no 'after' option.  There is a `cycle-after` event which you can listen for.

```
$( '#mySlideshow' ).on( 'cycle-after', function( event, opts ) {
    // your event handler code here
    // argument opts is the slideshow's option hash
});
```

http://jquery.malsup.com/cycle2/api/#events
