### ISSUE TITLE
Carousel API

### ISSUE THREAD

**Issue by christianmagill** [malsup/cycle2#472]
Is it possible to use the Carousel plugin through the API? I'd much prefer that to data attributes on the HTML but I don't see any such examples on the site.

Thanks

**Comment by malsup** [comment]
Anything that can be done declaratively can also be done programmatically.  Just camelCase the option names and drop the "data-cycle" bit.  For example, `data-cycle-carousel-visible` becomes `carouselVisible`.

**Comment by christianmagill** [comment]
Nice! Much thanks
