### ISSUE TITLE
Adding slides after specific index.

### ISSUE THREAD

**Issue by dog5tar** [malsup/cycle2#48]
Hi malsup,

I was using $(el).cycle('add', newSlide) and the one thing I'm missing right now is adding slide after specific index, similar functionally you have right now with removing slide by zero-based index.

What would be the best way to go about that?

Cheers!

**Comment by malsup** [comment]
That's not supported by C2 and it really sounds like an extreme edge case.  You can either append or prepend slides to the container with the "add" command.  To prepend, add a third argument of `true`.

**Comment by dog5tar** [comment]
Hi malsup,

well... it's not that extreme :)

You have an example which displays tweets in a vertical carousel. Imagine this scenario.

Every minute an AJAX call is made to fetch new tweets. When a new tweet comes, it should be inserted just after currently showed slide. Appending new tweets leaves user "out of date" as it might take minutes to cycle to new tweets.

Let me know your thoughts on this.

**Comment by malsup** [comment]
I would argue that the tweets should always be in chronological order and that inserting new ones somewhere in the middle doesn't make sense.  Given that, I suggest either appending or prepending the new slides and then programmatically advancing the slideshow to the desired slide index.

See 'goto' docs:  http://jquery.malsup.com/cycle2/api/#commands

**Comment by ManickYoj** [comment]
Thank you for answering the question about prepending! I've been looking all over for that!

**Comment by misund** [comment]
I have been looking for how to prepend for about an hour. I guess it could be really helpful for others if something about the prepend option were to be included in the API documentation.
