### ISSUE TITLE
Before & After Callback Functions not working on first slide

### ISSUE THREAD

**Issue by javistuff** [malsup/cycle2#49]
Hey Mike! First of all, great stuff on Cycle 2.. it's really an upgrade! Thanks for that!

I'm experiencing a bug with the slider not running the Before and After callbacks on the first slide. It's just happening on the first time the first slide appears and afterwards they are running as usual. So it's just happening on the very first slide.

Any clue on what to modify to solve that?

P.S. Functions are binded on "on" as in the documentation and called on document.ready.

**Comment by malsup** [comment]
The aren't fired for the first slide because there isn't actually a transition for that slide.  The before and after events demark transitions.  But you could write your after handler like this:

```
$( '.cycle-slideshow' ).on( 'cycle-initialized cycle-after', function( e, opts ) {...
```

In this case you're binding to two events.  cycle-initialized will fire one time, when the slideshow is initialized and it's first slide is displayed.

**Comment by javistuff** [comment]
I tried that before... I even tried firing an alert just on the cycle-initialized event, and nothing. It wont fire it.
I'm using the standard download version (the one around 17k) and some of the plugins. This should be working natively from the core, right? 
Also, regarding the "before" issue, I'm adapting the script from the one that worked before with Cycle 1. In that case, the "before" callback fired even on the first slide (weird?) and set the scope to the current slide. I tested it now and it is setting the scope to the whole "slideshow container".

**Comment by malsup** [comment]
Yes, Cycle and Cycle2 are different plugins with different event models.  With Cycle2, all events fire at the container context (slides and properties can be accessed via arguments to the event handler).

If the cycle-initialized event is not firing for you then that likely means you're binding that event handler after the event has already fired.

**Comment by javistuff** [comment]
Alright..!
I got it working. Somehow it wasn't firing, now it does.
Now hands on getting that slide before the transition.
Thanks a lot!
