### ISSUE TITLE
Fix Cycle2 fx:Fadeout for IE 7 and 8

### ISSUE THREAD

**Issue by archguru** [malsup/cycle2#491]
Before
opts.cssBefore = $.extend(css, { opacity: 1, visibility: 'visible', display: 'block' });

After
opts.cssAfter = $.extend(css, { opacity: 0, visibility: 'hidden' });
opts.cssBefore = $.extend(css, { opacity: 1, visibility: 'visible', display: 'block' });

Cheers ^^

**Comment by malsup** [comment]
Thanks.
