### ISSUE TITLE
swipe plugin: swipe-fx dont work.

### ISSUE THREAD

**Issue by jnz31** [malsup/cycle2#495]
hi
i tried to change the fx for swipe with data-cycle-swipe-fx="scrollHorz", but that doesnt change anything. data-cycle-swipe="true" works fine. plus: id like to use a different speed, since i use fx: "none" on click (speed: 1) and want to use another speed (obviously) for scrollHorz. (i changed speed for testing, but the swipe-fx wont do eather).
or should i use jquery ui? an update on how to solve this would be great.

**Comment by jnz31** [comment]
i changed my settings now. first i called cycle via js, just the swipe settings via data-attributes. i now switched to complete data-attribute. here is my log:

[cycle2] --c2 init--
[cycle2] swipeFx: scrollHorz (string)
[cycle2] swipe: true (boolean)
[cycle2] fx: fade (string) < makes no difference, if i set cycle-fx or not.
[cycle2] speed: 400 (number)
[cycle2] timeout: 0 (number)
[cycle2] slides: > article (string)

the transition on mobile and desktop is fade.
tested this on my iphone5, ios7.1

as i said above, best for me would be to set speed to 1 with fx=none, and set another speed for the swipe-fx.

**Comment by malsup** [comment]
There isn't an option for swipe speed, but the demo page shows the swipe-fx option working:

http://jquery.malsup.com/cycle2/demo/swipe.php

**Comment by jnz31** [comment]
hi mike
thanks for the reply. you are right, i wasnt working with the latest files. works now.
the "thing" with the speed is: if i set fx to none, the speed is still 400 (default), resulting in overlapping images (the new image appears, while the old image is still visible). this works fine, if i set the speed to 1, but then it would be best, to define a swipe-speed..
guess fx none shouldnt use the speed parameter..?

**Comment by sjamaan** [comment]
How did you manage to get this to work? I can only get it to work by overriding "fx". If I grep the sources for "swipefx", nothing shows up at all.

**Comment by malsup** [comment]
Sounds like you haven't downloaded the latest code.

https://github.com/malsup/cycle2/blob/master/build/jquery.cycle2.js#L1334

**Comment by sjamaan** [comment]
This hasn't been released yet, then? I am using the latest bower package.

**Comment by malsup** [comment]
I forgot to tag the release.  Just did that now.

**Comment by sjamaan** [comment]
Cool! Thanks for the quick action!
