### ISSUE TITLE
Disable log

### ISSUE THREAD

**Issue by FlashJunior** [malsup/cycle2#5]
I use the "Default Slideshow" with some configurations:

jquery.cycle2.min.js (BETA-20120923)
jquery.cycle2.tile.min.js (BETA-20120923)

```
<ul class="cycle-slideshow" 
    data-cycle-timeout="5000"
    data-cycle-pause-on-hover="true"
    data-cycle-speed="500"
    data-cycle-slides="> li"
    data-cycle-fx="tileSlide"
    >
        <li> <img src="image1.png" alt="" /></li>                   
        <li> <a href="/lorem/"><img src="image2.png" alt="" /></a></li>
        <li> <a href="/ipsum"><img src="image3.png" alt="" /></a></li>              
</ul>
```

And i see those console.log's:
[cycle2] --c2 init--
[cycle2] fx: tileSlide (string)
[cycle2] slides: > li (string)
[cycle2] speed: 500 (number)
[cycle2] pauseOnHover: true (boolean)
[cycle2] timeout: 5000 (number)

can i disable that?

if i'm in development, its cool - but if i go live with a project, would be good i could disable it.

**Comment by malsup** [comment]
You can disable logging by adding the following attribute:

```
data-cycle-log="false"
```

Just updated the docs to reflect this.

**Comment by FlashJunior** [comment]
PERFECT!

**Comment by FlashJunior** [comment]
Website is now online http://www.bommeli.net/
Thanks for your great work!

**Comment by weshardee** [comment]
Is there any way to set this globally? It's a bit annoying to have to turn it off element by element. I feel like this value would be more useful if set to false by default.

**Comment by malsup** [comment]
Adding this to your page should provide global control.

```
<script>$.fn.cycle.log = $.noop</script>
```

**Comment by gazjoy** [comment]
When I add the above cycle.log script to my site I get an error.

Uncaught TypeError: Cannot read property 'cycle' of undefined
(anonymous function)

I have tried adding it before and after the cycle plugin and at the end of the document </body>. Any ideas on why it throws this error?
