### ISSUE TITLE
Problem with sentinel-slilde and id

### ISSUE THREAD

**Issue by SLemming** [malsup/cycle2#50]
I really, really like your cycle2 plugin for all my mobile sliders.
But the sentinel slide can cause several problems, if a pane or some of its children have an id. So this id is doubled when a sentinel slide is created which leads to incorrect results when using document.getElementById or (inQuery) $('#id'). It only returns the first (= the one in the sentinel) element.
The only solution right now is not to use a dynamic height (so no sentinel slide is created), but I would like to use auto-height="calc" AND ids.

**Comment by malsup** [comment]
Good catch, thanks!  Fixed now.

**Comment by SLemming** [comment]
Great, thanks for the quick fix :)

**Comment by michelgotta** [comment]
Many lightbox plugins use the `rel` Attribute to invoke the lightbox function. Maybe this should be removed too, to avoid having the sentinel in the lightbox.

**Comment by malsup** [comment]
Good call @michelgotta.

**Comment by digitaldesigndj** [comment]
What do you mean by "Sentinel Slilde", are you talking about the first slide?

**Comment by michelgotta** [comment]
@digitaldesigndj The "Sentinel-Slide" is the invisible first slide defining the height of the Slideshow. If this is cloned by another slide it has the `rel` attribute too. Lightbox Plugins like Colorbox or Slimbox etc. use this.

**Comment by malsup** [comment]
As michelgotta mentioned, the sentinel slide is a special slide that cycle2 optionally uses to manage slideshow height. More info here:  http://jquery.malsup.com/cycle2/demo/autoheight.php

**Comment by Ahaenor** [comment]
Fresco Lightbox uses class attribute. Can class also be removed from sentinels?
