### ISSUE TITLE
Set transition when using commands

### ISSUE THREAD

**Issue by superbia** [malsup/cycle2#500]
Is there a way to set the transition when using a command like 'goto' or directly using the  jump function in the commands api? I'd like to use a custom transition I've made for the prev and next controls and the fade transition when using the pager.

Thanks.

**Comment by malsup** [comment]
I just added support for pager-specific transitions via the `data-cycle-pager-fx` attribute.  

http://jquery.malsup.com/cycle2/demo/pager.php#fx

Also, goto/jump now support an additional argument to identify the fx override.

**Comment by superbia** [comment]
That's fantastic, thanks!
