### ISSUE TITLE
Is there a way to prevent auto running?

### ISSUE THREAD

**Issue by ianthedev** [malsup/cycle2#504]
Though using `.cycle('stop')` stops it immediately after initialization, it starts auto runing after clicking "Next" button.

**Comment by Alderan184** [comment]
maybe that would do the thing: data-cycle-timeout=0

**Comment by ianthedev** [comment]
@Alderan184, that works. Thanks.

**Comment by theleewise** [comment]
Or what about data-cycle-paused=true

**Comment by malsup** [comment]
If you don't want auto-initialization you can add the following attribute to your slideshow element:

```
data-cycle-auto-init=false
```

**Comment by ianthedev** [comment]
I tried setting that via javascript way, but it doesn't work.

``` javascript
autoInit: false
```
