### ISSUE TITLE
pause on hover and previous/next buttons

### ISSUE THREAD

**Issue by weshardee** [malsup/cycle2#51]
If you use pause-on-hover and have navigation buttons that are outside of the main 'cycle-slideshow' div, the slideshow does not pause when the buttons are hovered.

**Comment by malsup** [comment]
It's not meant to work that way.  pause-on-hover only pauses the slideshow when the mouse is over the slideshow.  You could do something like this:

```
$('#myPauseButton').hover(function() {
    $('#mySlideshow').cycle('pause');
}, function() {
    $('#mySlideshow').cycle('resume');
});
```

**Comment by weshardee** [comment]
That's what I'm doing, but it feels like a bandaid. Why isn't this the standard behavior? Automatic rotation + nav buttons that don't pause the slideshow = an awkward user experience. Pressing 'prev' when the slideshow keeps automatically advancing is annoying.

**Comment by malsup** [comment]
It's not standard behavior because I never thought of it.

**Comment by weshardee** [comment]
Ah. Well consider this a feature suggestion :) Also thanks for the great work thus far. This plugin is wonderful.

**Comment by malsup** [comment]
Well, after checking the code it turns out this was already supported, but in a non-obvious (and non-documented) way.  I've just updated the docs to reflect the fact that you can set the `data-cycle-pause-on-hover` attribute value to a selector string which identifies the element(s) to which the hover events should be bound.  For example:

```
data-cycle-pause-on-hover=".cycle-slideshow,.cycle-pager"
```

**Comment by weshardee** [comment]
That looks great. Thanks for looking into this.

**Comment by sebheg** [comment]
Cycle2 is such a nice plugin! Haven't played with it in a while, and as I implemented Cycle2 with pauseOnHover today, I came across this post... Thanks a lot, Mike!!
