### ISSUE TITLE
Cycle2 declarative commands and initialisation 

### ISSUE THREAD

**Issue by nckprsn** [malsup/cycle2#518]
Hi all,

I'm having a problem using the declarative commands with Cycle2 and keep getting this message in the console:

```
[cycle2] slideshow must be initialized before sending commands; "goto" ignored 
```

The elements in question look like this:

```
<ul>
    <li class="myclass" data-cycle-cmd="goto" data-cycle-context="#slideshow" data-cycle-arg="1">content</li>
    <li class="myclass" data-cycle-cmd="goto" data-cycle-context="#slideshow" data-cycle-arg="2">content</li>
    (...)
</ul>
```

What am I missing? Is there anything else that needs to be included before declarative commands like this can be used?

I have also tried doing this in a different way, with this:

```
$( document ).on( 'cycle-post-initialize' , '#slideshow' , function()
{
    var slideshow = $( '#slideshow' );

    slideshow.on( 'click' , '.slide_index_panel' , function()
    {
        var goto_index = $( this ).data( 'slide-index' );
        slideshow.cycle( 'goto' , goto_index );
    });
});
```

(with the aforementioned li elements updated with a "data-slide-index" attribute)

This produces the same error message in the console.

Any suggestions would be most welcome.

**Comment by ouroborus** [comment]
If you're getting that log message, you should also be getting the log messages about initialization of the carousel. If you are not getting those initialization messages (and assuming logging is still on for that carousel), you'll need to figure out why the carousel is not being initialized. If you are getting the initialization messages, then it's likely the slideshow isn't actually on the `#slideshow` element.

**Comment by nckprsn** [comment]
Thanks @ouroborus - the slideshow wasn't on the #slideshow element. I hadn't realised because cycle-post-initialize was still being fired!
