### ISSUE TITLE
pictures wobble 1pixel when changing to next slide

### ISSUE THREAD

**Issue by cares** [malsup/cycle2#520]
hi guys...

first: thanks for the awsome free cycle1 and 2 plugins ;)

now the problem: did you notice a 1px move of the current picture... when changing to next picture?

(firefox 29.0.1... but not in chrome!?)

may sound not that much... but it looks pretty evil... if you have a 1px border around your slideshow-div

i did not realize such a problem with the cycle1 plugin.

it is even visible on the fist slideshow on your page: http://jquery.malsup.com/cycle2/demo/basic.php
(watch very closely)

this kind of makes the plugin completely unusable for my current project... argh.

take care.

**Comment by malsup** [comment]
Search this issues, this has been discussed before.

**Comment by FlashJunior** [comment]
@cares checkout https://github.com/malsup/cycle2/issues/403
add `.cycle-slide img{box-shadow:#fff 0 0 0;}` to your css

**Comment by cares** [comment]
wow. that was fast thx a lot. tested and approved (y) big thanks. :+1:
