### ISSUE TITLE
Sync Slideshow panels visible

### ISSUE THREAD

**Issue by kaspar-allenbach** [malsup/cycle2#54]
Hi.

I made two syncronized slideshows here: http://sonjamuehlemann.ch/
On the right side the slideshow only contains text. Now the problem is, that the slides behind the active slide are still visible. This results in three texts over each other. I now added a background to each slide. But I would like to have no background at all.

How do I do this?

Thank you.

**Comment by malsup** [comment]
You've got some css rules on that page that are causing sentinel content to be displayed.  Try adding this rule:

```
.cycle-sentinel * { visibility: hidden; }
```

Also, change `hide-non-active` to `data-cycle-hide-non-active`
