### ISSUE TITLE
Unable to disable console logging using $.fn.cycle.defaults.log

### ISSUE THREAD

**Issue by majokmet** [malsup/cycle2#541]
Hello,

it seems that property $.fn.cycle.defaults.log is ignored by the plugin. Even though It's set as false before calling cycle(), the messages are still being displayed in console.

Standard  .cycle ({ log: false }); works fine, however I would prefer to initialize cycle without arguments, using defaults.

Thanks! Keep up good work

**Comment by malsup** [comment]
Check the FAQ. 

http://jquery.malsup.com/cycle2/faq/

**Comment by majokmet** [comment]
That means that I have to redefine "data-cycle-log" attribute for every slideshow container. It's not a big deal, but it would be cleaner just to change that $.fn.cycle.defaults.log (modifying other properties in $.fn.cycle.defaults object seems to work correctly - except of "log").

**Comment by malsup** [comment]
There is no $.fn.cycle.defaults.log property in C2.  But this should work:

$.fn.cycle.log = $.noop;

**Comment by majokmet** [comment]
This works fine, thank you!
