### ISSUE TITLE
How to set up random effects?

### ISSUE THREAD

**Issue by suxpert** [malsup/cycle2#55]
I don't know where to ask, so post it here, forgive me :)

It's quite cool that cycle2 has provided some kind of effects on this slides, but it seems that the effect must be either a same one, or some fixed ones coming with the image. I've tried to use a timer to modify the `data-cycle-fx' attribute, but it does not work (because cycle2 will init only once?).

So, how can I do for a random effect if I want to use cycle2? Or, will such a feature be added in some newer version?

**Comment by malsup** [comment]
Perhaps that will be added in a future version but it's not currently supported out of the box.  Instead of modifying the data-cycle-fx attr on the slide try modifying the `fx` property on the slide's data object.  I haven't actually tested this, just trying to give you something else to try:

```
// change first slide's fx
$('.cycle-slideshow').find('.cycle-slide:eq(0)').data('cycle.opts').fx = 'fade'
```

**Comment by suxpert** [comment]
Thanks for your suggestion. Unfortunately, it seems that this snippet of code can not work, or I've made some other mistakes :(
I'll check out the document first.

**Comment by Gtrujillo** [comment]
I know this is an oldie, yet I still find myself wanting this feature.
