### ISSUE TITLE
Problem with progressive loading in Opera

### ISSUE THREAD

**Issue by martinpesout** [malsup/cycle2#56]
Hi,

I'm trying to implement progressive loading of images in Opera 12.11. And this plugin doesn't work. I see no problem in browser console. Is it possible to fix this problem?

Example http://jquery.malsup.com/cycle2/demo/progressive.php

Thanks a lot.

Martin

**Comment by martinpesout** [comment]
I've done some testing. The problem starts when I set additional attribute loader

**Comment by malsup** [comment]
I think I see why this is failing.  Opera doesn't actually load the image until it is inserted into the DOM, the other browsers load the image when the new element is created.  I'll need to refactor a bit to account for that behavior.

**Comment by Luk4** [comment]
Hi Malsup! First of all, thanks for this great plugin -- I have tried a ton of plugins and yours is the only one which works in my layout (BS 2.3 template, infinite scrolling of multiple AJAX-loaded galleries only loading images as they are needed).

The only problem I run into so far is the fact that appending the new image to the body with .css('visibiity','hidden') breaks the layout (tested in FF, IE and Chrome) by displaying a scroll bar that was supposed to remain hidden. If I change that .css('visibiity','hidden') into a .css({'display':'none'}) the layout stays as it is supposed to.

Now my question is: is it ok to use display:none or Opera users will run into trouble?

Thanks for your advice on this!

**Comment by maryisdead** [comment]
Having the same issue as @Luk4: `visibility: none` can break many things layout-wise since it doesn't take the element out of flow. In my case I had some miles of whitespace at the bottom of the page because of slides being appended to `<body>`.

What's the reasoning behind this?
