### ISSUE TITLE
Adding <a href around slide breaks it

### ISSUE THREAD

**Issue by rachatfig** [malsup/cycle2#567]
Hey, 
Adding <a href= around each slide makes the slider stop working and display the slides in a block down the page.

**Comment by JayV416** [comment]
Hi I just had this same problem just now and i found a solucion here https://github.com/malsup/cycle2/issues/214

Hope it helps.

Sample of the code:

<div class="cycle-slideshow" data-cycle-slides=".cycle-link" >
    <a href="Your URL goes Here" class="cycle-link" data-cycle-title="Overlay Title" data-cycle-desc="Overlay Description"><img src="Your Img. Source" /></a>
    
</div>

**Comment by richgcook** [comment]
@rachatfig You need to make the `<a>` element a block element, and width:100%.

**Comment by rachatfig** [comment]
Thanks both.
