### ISSUE TITLE
Firefox image position slightly out on transition

### ISSUE THREAD

**Issue by bdgeorge** [malsup/cycle2#570]
When viewing any cycle in firefox new images seem to transition in slightly out of position and then bump into place, they are about 1px out both vertically and horizontally and then it corrects with a very obvious visual jerk.

You can see this on the official basic demo page:http://jquery.malsup.com/cycle2/demo/basic.php

It's much more obvious if you have a cycle container that lines up with other elements on the page

This has the same symptoms as closed issue #256, however it's not related to bootstrap or the 45% width setting - I've seen it on every site I've found using cycle2 with the current Firefox version (checked against FF 31.0 on OSX 10.8 and 10.9).

Chrome, Safari are still fine.

**Comment by bdgeorge** [comment]
To add to this, the issue seems to be triggered by CSS margin resets on the body element.
On the demo page (http://jquery.malsup.com/cycle2/demo/basic.php) in site.css if you edit the CSS in firebug you can remove the issue by remove the 0 margin reset from the body element.

eg change

```
html, body, div, h1, h2, h3 {
margin: 0;
padding: 0;
}
```

to 

```
html, div, h1, h2, h3 {
margin: 0;
padding: 0;
}
```

and the problem goes away.

The same thing can be seen in cycle1 and other cycle plugins like flexslider - if the body element resets the margin to 0 the 'jiggle' bug appears in Firefox only.

**Comment by FlashJunior** [comment]
checkout #403, #520 
add `.cycle-slide img{box-shadow:#fff 0 0 0;}` to your css

**Comment by bdgeorge** [comment]
Thanks @FlashJunior I'd been headbutting this one for ages!
