### ISSUE TITLE
timeoutFn

### ISSUE THREAD

**Issue by blowsie** [malsup/cycle2#58]
What happened to `timeoutFn` found in cycle v1? 

I looked through the API but couldn't see it.

**Comment by malsup** [comment]
It doesn't exist in Cycle2.  If you need slide specific timeouts then use the `data-cycle-timeout` attribute on your slides.

**Comment by blowsie** [comment]
I actually use the function do make the timeouts vary, see this for example. http://twatboutique.com/

Note:  **softcore content**

**Comment by malsup** [comment]
That same functionality is not provided by cycle2.  You could manipulate the per-slide options manually via script, or continue to use cycle1 for that behavior.
