### ISSUE TITLE
Wrong sourceMappingURL in jquery.cycle2.js.map causes Chrome 404

### ISSUE THREAD

**Issue by robfaas** [malsup/cycle2#603]
jquery.cycle2.min.js - last line is: 
//# sourceMappingURL=jquery.cycle2.js.map

In Chrome (not in other browsers) this leads to a 404 because of request for non existing file jquery.cycle2.js.map

**Comment by nathanaelphilip** [comment]
+1

**Comment by jb67268** [comment]
+1

**Comment by eberkund** [comment]
+1

**Comment by axyr** [comment]
+1

**Comment by greenxd** [comment]
+1

**Comment by oleglopeta** [comment]
+1

**Comment by stat1x** [comment]
+1

**Comment by malsup** [comment]
Source map comment removed from: http://malsup.github.io/min/jquery.cycle2.min.js

**Comment by robfaas** [comment]
Wow! :)
