### ISSUE TITLE
Cycle to Cycle2

### ISSUE THREAD

**Issue by Karttin** [malsup/cycle2#608]
In cycle version I was able to set fx for each image. Is there any reason why its not carried over to cycle 2?

I tried this
&lt;div class="cycle-slideshow" data-cycle-fx="scrollHorz,fadeOut,tileSlide"    data-cycle-speed="750" data-cycle-timeout="3000" data-cycle-pager=".cyclepager"&gt;
                &lt;div class="cycle-pager"&gt;&lt;/div&gt;
                  &lt;img src="http://malsup.github.io/images/beach1.jpg" width="200" height="200"&gt;
            &lt;img src="http://malsup.github.io/images/beach2.jpg" width="200" height="200"&gt;
            &lt;img src="http://malsup.github.io/images/beach3.jpg" width="200" height="200"&gt;
            &lt;/div&gt;
            &lt;div class="cyclepager"&gt;&lt;/div&gt;
Unfortunately its not liking it. Any other suggestions please

Kind Regards
Kay

**Comment by malsup** [comment]
In C2 the `fx` attr can go on the slide:

```
<img src="whatevs.jpg" data-cycle-fx="fade">
```

http://jquery.malsup.com/cycle2/api/
