### ISSUE TITLE
Bug in parsing of declarative timeout 

### ISSUE THREAD

**Issue by lilith** [malsup/cycle2#61]
The 'data-cycle-timeout' value, when parsed as a string instead of an integer, later causes issues by concatenating to 'delay' instead of adding as a number. 

line 147:

```
      opts.timeoutId = setTimeout(function() {
            opts.API.prepareTx( false, !opts.reverse );
        }, opts.timeout + opts.delay);
    }
```

**Comment by malsup** [comment]
?

Under what case would it be parsed as a string?  As stated in the docs, `timeout` accepts integer values.

**Comment by lilith** [comment]
$("<div />").data("cycle-timeout","500") will do it. I haven't tested plain markup to see if it happens there as well or not.

**Comment by malsup** [comment]
Don't do that!  ;-)

It won't happen with the data-cycle-timeout attribute because jQuery's `data` method will convert data-\* attrs to their primitive values.  I'm not planning to add parseInt code for all possible attributes that can be misused.

**Comment by lilith** [comment]
Fair enough :)
