### ISSUE TITLE
continueAuto not working

### ISSUE THREAD

**Issue by funkybudda** [malsup/cycle2#615]
hello,

anyone able to get "continueAuto" working correctly? Trying setting the value via cycle.opts and when change from either true boolean value to false, the slider just keeps going.

Ideally, I need my cycle2 slider to stop looping (not just pausing) once user interact with certain elements on the page, if anyone has a better suggestion, please share it with me.

Thanks in advance.

**Comment by funkybudda** [comment]
any update? At least an acknowledgement of this being a actual bug?

**Comment by malsup** [comment]
It works, but perhaps not the way you expected.

http://jquery.malsup.com/cycle2/demo/continue-auto.php
