### ISSUE TITLE
Include jquery.cycle2.min.js twice in one page.

### ISSUE THREAD

**Issue by subhomalik** [malsup/cycle2#619]
Hello,
I need to include jquery.cycle2.min.js for every slider.But having jquery.cycle2.min.js multiple times my sliders conflicting.I know we can easily include one cycle2.min for unlimited slider.But my requirement is different. Below is my code example what i am looking for.
`<script type="text/javascript" src="jquery-1.10.2.min.js"></script>`
`<script type="text/javascript" src="jquery.cycle2.min.js "></script>`
`<div class="cycle-slideshow">`
 [slider 1] 
 `</div>`

`<script type="text/javascript" src="jquery-1.10.2.min.js"></script>`
`<script type="text/javascript" src="jquery.cycle2.min.js "></script>`
`<div class="cycle-slideshow">`
 [slider 2] 
 `</div>`

 PLZ help me as soon as you can.

**Comment by kn00tcn** [comment]
why do you need to include it more than once? use ID instead of CLASS?

**Comment by malsup** [comment]
No, don't do that.
