### ISSUE TITLE
loader="wait" does not preserver order when > 8 images are used

### ISSUE THREAD

**Issue by lilith** [malsup/cycle2#65]
The comparator function does not return the proper values, causing incorrect sorting.

Comparator functions are required to evaluate to 0 when a==b, negative when a should occur before b, and positive when b should occur before a. 
ref: https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Array/sort

Current code:

```
    function sorter(a, b) {
        return a.data('index') > b.data('index');
    }
```

Code that resolves the issue: 

```
    function sorter(a, b) {
        return a.data('index') - b.data('index');
    }
```

Reproduced on: Chrome 23.0.1271.97

**Comment by malsup** [comment]
Good catch, thank you.

**Comment by rpontes** [comment]
Thanks, my problem was that...
