### ISSUE TITLE
Override maxZ value

### ISSUE THREAD

**Issue by gforcada** [malsup/cycle2#653]
Hi,

We are using cycle2 on our website to add galleries and we have some static toolbars that are placed statically above all content.

From what we understood, each slide is given, at maximumm `$.fn.cycle.defaults.maxZ` as value for z-index.

Our first approach was to just add `data-cycle-maxZ="5"` to our div element, but our HTML preprocessor was lowercasing it.

Then we tried adding it with JavaScript without success either:

```
<script>
var i, galleries, gallery;
galleries = document.getElementsByClassName('gallery');
for (i=0; i<galleries.length; i++) {
    gallery = galleries[i];
    gallery.setAttribute('data-cycle-maxZ', '50');
}
</script>
```

So at the end we just patched cycle2 to change the default from 100 to 10 (our value of choice).

Did we do something wrong, is actually `maxZ` meant to be overriden? Is there a possibility to change it to lowercase so that it works with HTML preprocessors?

Thanks for the library, apart from this small issue, we are really happy with it!

**Comment by itwasmattgregg** [comment]
+1

I would love to see this changed as well so the z-index can be manipulated via the data attributes. Would prevent having to edit the plugin code myself. It works with lowercase variable name.

**Comment by gforcada** [comment]
As the project has no longer activity, there's no point on keeping this issue open 🙂
