### ISSUE TITLE
highly customized overlay

### ISSUE THREAD

**Issue by pirco** [malsup/cycle2#66]
I'm trying to add a highly customized "project description"  in an overlay on top of the images. the overlay template has too many limitations for my purposes so I'm just adding div class='project-description'> . the_content() . /div (yes, I'm using this within a wordpress template. "the_content()" pulls lots of text and images and custom scrollbars etc) but  the_content()  appears outside of the "project-description" div in the rendered page.

**Comment by malsup** [comment]
Here's an example of one way to approach this issue.   You just need to think outside the box a little bit to see the possibilities:

http://jquery.malsup.com/cycle2/demo/overlay-custom.php

**Comment by malsup** [comment]
Another approach can be found in the "Composites" section of this page:  http://jquery.malsup.com/cycle2/demo/non-image.php

**Comment by pirco** [comment]
thank you!
