### ISSUE TITLE
autoHeight "container" Demo doesn't work.

### ISSUE THREAD

**Issue by FlashJunior** [malsup/cycle2#666]
http://jquery.malsup.com/cycle2/demo/container-resize.php

Tested on:
- OSX: Chrome 40, Firefox 36
- Win7: IE 11, IE 9

i just see the first image. If i click "prev/next" i see the event firing but no image switch.

**Comment by FlashJunior** [comment]
any update on that?

**Comment by malsup** [comment]
The image placeholder site I was using wasn't working correctly.  Changed to a different one.
