### ISSUE TITLE
Carousel Plugin: Too Many Active Classes

### ISSUE THREAD

**Issue by duebel** [malsup/cycle2#67]
I'm trying to display the overflow of the carousel so that it shows slides to the left and right of the "active"  slide. I've set the CSS of the container to show the overflow. But, there appears to be an active state assigned (fixed) to every other slide and I can't seem to over-ride this. At first, this isn't a problem, until the slide animation happens and we have 3 active slides beside one another: http://mbu.dev.integritystl.com/

**Comment by ShaunaGordon** [comment]
Have you tried setting "carousel-visible" to "3", instead of trying to build that effect manually?

**Comment by malsup** [comment]
I think this is fixed now.

**Comment by malsup** [comment]
Hang on, Github isn't serving the right version yet.

**Comment by malsup** [comment]
Looks ok now.

http://malsup.github.com/jquery.cycle2.carousel.js

Should be version: 20130108
