### ISSUE TITLE
Responsive Carousel Number Of Items

### ISSUE THREAD

**Issue by adoumas** [malsup/cycle2#68]
Hello again,

Im trying to find a way to change the carouselVisible items in a responsive design.

i want in a screen resolution of 1200px to show 3 items. and when you scale down in 768 to have 2 items and in 320px 1 item.

is that possible? i did try to change carousel option on load or resize but it didnt work.

<pre>
<code>
$cycle = $('.cycle-slideshow')
$cycle.each(function(index, element) {
    if ($(element).hasClass('carousel')) {
        $(window).resize(function(e) {
            $(element).cycle({'carouselVisible':1}).cycle('reinit');
        });
    }
});
</code>
</pre>

or this way 

<pre>
<code>
$cycle = $('.cycle-slideshow')
$cycle.each(function(index, element) {
if ($(element).hasClass('carousel')) {
        $(window).resize(function(e) {
            $(element).attr('data-cycle-carousel-visible',1).cycle('reinit');
        });
    }
});

</code>
</pre>

thx again for the great plugin!

**Comment by benschaaf** [comment]
I'm after this same functionality. You get anywhere with this alexdoumas?

**Comment by malsup** [comment]
There's no built in support for changing the number of slides in a carousel.  So maybe just and a matchMedia event handler and in the callback grab the current slide index, then destroy and restart with the startingSlide value set.

**Comment by benschaaf** [comment]
Hmm. I am trying to digest that comment. Doesn't reinit do the same thing? I came up with this wacky thing. It works on the first load, but if users resize their browser window, not so much.  However, it would be great if they could. Can you comment on this mess of mine and suggest something better?

Once this is working, I would be happy to throw together a video tutorial for folks trying to do the same thing.

On page load, I check the document width and then serve up the correct slideshow (probably not very efficiently). Then on window resize, I try to reinit the slideshow passing the carouselVisible value as a variable.

`````` javascript
function initCycle() {
        var width = $(document).width();
        // console.log('Init doc width: ' + width);
        if ( width < 768 ) {
            $('.brand-list').cycle({
                fx: 'carousel',
                speed: 600,
                manualSpeed: 100,
                slides: '> li > ul',
                next: '.next',
                prev: '.prev',
                carouselVisible: 2,
                carouselDimension: '180px'
            });
            // console.log('Init Mobile');
        } else if ( width > 768 && width < 980 ) {
            // console.log('Init Tablet');  
            $('.brand-list').cycle({
                fx: 'carousel',
                speed: 600,
                manualSpeed: 100,
                slides: '> li > ul',
                next: '.next',
                prev: '.prev',
                carouselVisible: 3,
                carouselDimension: '180px'
            });     
        } else {
            // console.log('Init Big');
            $('.brand-list').cycle({
                fx: 'carousel',
                speed: 600,
                manualSpeed: 100,
                slides: '> li > ul',
                next: '.next',
                prev: '.prev',
                carouselVisible: 4,
                carouselDimension: '180px'
            });
        }
    }
    initCycle();


    function reinit_cycle() {
        var wWidth = $(window).width();
        if ( wWidth < 768 ) {
            console.log( 'Resized and mobile ' + $(window).width() );
            reinitCycle(2);
        } else if ( wWidth > 768 && wWidth < 980 ) {
            console.log( 'Resized and tablet ' + $(window).width() );
            reinitCycle(3);
        } else {
            console.log( 'Resized and big ' + $(window).width() );
            reinitCycle(4);
        }
    }
    function reinitCycle(visibleSlides) {
        console.log(visibleSlides);
        $('.brand-list').cycle({
            fx: 'carousel',
            speed: 600,
            manualSpeed: 100,
            slides: '> li > ul',
            next: '.next',
            prev: '.prev',
            carouselVisible: visibleSlides,
            carouselDimension: '180px'
        });
    }
    var reinitTimer;
    $(window).resize(function() {
        clearTimeout(reinitTimer);
        reinitTimer = setTimeout(reinit_cycle, 200);
    });```
``````

**Comment by malsup** [comment]
Just calling cycle() again doesn't do anything.  You need to destroy it first, then reinit.  For example:

```
$('.brand-list').cycle( "destroy" )
reinitCycle(2);
```

**Comment by benschaaf** [comment]
I will try it now. Thanks malsup! Sorry to be a pest!

**Comment by benschaaf** [comment]
( ﾟヮﾟ)/    Yay!

That seemed to do the job. Awesome. If anyone has suggestions to clean this up, please let me know.

I will post the tutorial link here. For now, the code:

``` javascript
    function initCycle() {
        var width = $(document).width(); // Getting the width and checking my layout
        if ( width < 768 ) {
            $('.brand-list').cycle({
                fx: 'carousel',
                speed: 600,
                manualSpeed: 100,
                slides: '> li > ul',
                next: '.next',
                prev: '.prev',
                carouselVisible: 2,
                carouselDimension: '180px'
            });
            // console.log('Init Mobile');
        } else if ( width > 768 && width < 980 ) {  
            $('.brand-list').cycle({
                fx: 'carousel',
                speed: 600,
                manualSpeed: 100,
                slides: '> li > ul',
                next: '.next',
                prev: '.prev',
                carouselVisible: 3,
                carouselDimension: '180px'
            });
        } else {
            $('.brand-list').cycle({
                fx: 'carousel',
                speed: 600,
                manualSpeed: 100,
                slides: '> li > ul',
                next: '.next',
                prev: '.prev',
                carouselVisible: 4,
                carouselDimension: '180px'
            });
        }
    }
    initCycle();

    function reinit_cycle() {
        var width = $(window).width(); // Checking size again after window resize
        if ( width < 768 ) {
            $('.brand-list').cycle('destroy');
            reinitCycle(2);
        } else if ( width > 768 && wWidth < 980 ) {
            $('.brand-list').cycle('destroy');
            reinitCycle(3);
        } else {
            $('.brand-list').cycle('destroy');
            reinitCycle(4);
        }
    }
    function reinitCycle(visibleSlides) {
        $('.brand-list').cycle({
            fx: 'carousel',
            speed: 600,
            manualSpeed: 100,
            slides: '> ul',
            next: '.next',
            prev: '.prev',
            carouselVisible: visibleSlides,
            carouselDimension: '180px'
        });
    }
    var reinitTimer;
    $(window).resize(function() {
        clearTimeout(reinitTimer);
        reinitTimer = setTimeout(reinit_cycle, 100); // Timeout limits the number of calculations   
    });
```

**Comment by tvgeit** [comment]
got this working, awesome, but is it possible to pass another argument on the reinitCycle?

i would like to have a vertical carousel (carouselVertical: true) on wider screens but a horizontal one (carouselVertical: false) when it's a tablet.

**Comment by wlanni** [comment]
@tvgeit 
Yes. You could add another argument into the function reinitCycle for carouselVertical:

```
function reinitCycle(visibleSlides, verticalBool) {
    $('.brand-list').cycle({
        fx: 'carousel',
        speed: 600,
        manualSpeed: 100,
        slides: '> ul',
        next: '.next',
        prev: '.prev',
        carouselVisible: visibleSlides,
        carouselDimension: '180px',
       carouselVertical: verticalBool
    });
}
```

Then, in your reinit_cycle() just call whichever you want.

**Comment by jnz31** [comment]
thanks for this solution. i tried myself in improving..
i changed the function a little bit, to make it only execute, IF the carouselVisible changes, NOT everytime, the window is being resized. therefor i change and check the data-cycle-carousel-visible attribute..
plus on resize, i made the slideshow jump to the current slide, not always the first one..

```
var cycle_check, cycle_init, cycle_timer, cycle_next, cycle_active = 0;

(cycle_check = function() {
    var width = $(window).width(); // Checking size again after window resize
    if ( width < 768 && $( ".slideshow" ).attr( "data-cycle-carousel-visible" ) !== "1" ) {
        $( ".slideshow" ).cycle( "destroy" ).attr( "data-cycle-carousel-visible", "1" );
        cycle_init( 1 );
    } else if ( width > 768 && $( ".slideshow" ).attr( "data-cycle-carousel-visible" ) !== "2" ) {
        $( ".slideshow" ).cycle( "destroy" ).attr( "data-cycle-carousel-visible", "2" );
        cycle_init( 2 );
    }
})();

function cycle_init( visibleSlides ) {
    $( ".slideshow" ).cycle({
        fx: "carousel",
        speed: 600,
        slides: "> img",
        carouselVisible: visibleSlides,
        timeout: 6000,
        startingSlide: cycle_active
    });
}

$(window).resize( function() {
    clearTimeout( cycle_timer );
    cycle_timer = setTimeout( function() {
        cycle_check();
    }, 100 );
});

$(".slideshow").on("cycle-update-view", function ( e, optionHash, slideOptionsHash, currSlideEl ) {
    cycle_active = optionHash.currSlide;
});
```

**Comment by Colir** [comment]
...i lloking for this feat too...i did'nt understand why this doesn't work...

When calling destroy, the cycle is remove, but the initCarousel function after doesn't init cycle...

thanks you very much

``` javascript
$(function(){
   $(window).on('resize',resizeHandler).resize()
})


function resizeHandler(){
   var nbVisibleSlide = ($(window).width >= 768) ? 6 : 3;
   $('.carousel-holder').cycle('destroy');
   initCarousel(nbVisibleSlide )
}

function initCarousel(nbVisibleSlide){
        $('.carousel-holder').cycle({
            speed: 600
            ,timeout:2500
            ,carouselFluid : true
            ,carouselVisible : nbVisibleSlide
            ,fx : 'carousel'
            ,slides :'.carousel-item'
            })
        }
```

**Comment by aric87** [comment]
I solved this with a very simple fix. I had carousel that had all the data-cycle-\* information I needed. So I changed the data-cycle-carousel-visible to the new number, destroyed, then restarted. The only issue was the opacity on the non-active slides was 0, so I changed the css: .cycle-slide{opacity:1 !important}
`function carouselResize(number){
var slider = $('.cycle-slideshow');
        slider.attr('data-cycle-carousel-visible',number);
        slider.fadeOut(200, function(){
            slider.cycle('destroy');
            slider.cycle();
            $(window).trigger('resize'); //causes the slides to resize correctly
            slider.fadeIn(200);
       }
}`

**Comment by helder0000** [comment]
Hi guys. This work very well, but the pager don't match the visible slides. Someone know how I can fix that?
Thanks!

**Comment by valiermedia** [comment]
This is a modified version of the code that @benschaaf posted, even though this is old I feel like this still comes up from time to time. What I found, is that when you destroy and re-invoke slideshows, the script will only replace HTML5 attribute options if different values are provided in the re-invocation code. See example below:

```
var video_carousels = $('.cycle-slideshow[data-cycle-fx="carousel"]');
    if(video_carousels) {
    	reinit_cycle();
    	var reinitTimer;
		$(window).resize(function() {
			clearTimeout(reinitTimer);
			reinitTimer = setTimeout(reinit_cycle, 100); // Timeout limits the number of calculations   
		});
    }

    function reinit_cycle() {
        var width = $(window).width(); // Checking size again after window resize
        if ( width < 768 ) {
            $(video_carousels).cycle( "destroy" );
            $(video_carousels).cycle({
            	carouselVisible: 2,
            });
        } else if ( width > 768 && width < 980 ) {
            $(video_carousels).cycle( "destroy" );
            $(video_carousels).cycle({
            	carouselVisible: 3,
            });
        } else {
            $(video_carousels).cycle( "destroy" );
            $(video_carousels).cycle({
            	carouselVisible: 4,
            });
        }
    }
```

First off, excuse the tab spacing issues in my code. There are several key components needed for this to work:

1. My HTML code declares options for each slideshow, such as setting the fx to carousel, setting the default number of visible slides, etc.

2. I cached all of the slideshows near the beginning of the code in the video_carousels variable, you can name this something more appropriate for your project (my slides are all video thumbnails)

3. I am only re-declaring the carouselVisible option, so when I resize the window, the reinitTimer detects a change, fires the reinit_cycle function, then destroys and re-invokes .cycle on the cached carousels and declares a new "carouselVisible" value. All of the other values are left intact, which helps avoid the need to re-declare every option when re-invoking.
