### ISSUE TITLE
Start slideshow in the middle

### ISSUE THREAD

**Issue by dantastical** [malsup/cycle2#692]
I want to be able to begin the slideshow on, say, the third slide (including having the pager showing it as the third slide) but can't find a good way to do this, there is the goto command but this shows the transition and isn't ideal. Any assistance would be much appreciated:)

**Comment by malsup** [comment]
http://jquery.malsup.com/cycle2/api/#starting-slide

**Comment by dantastical** [comment]
I have no idea how I missed that, thank you so much!
