### ISSUE TITLE
Using data-cycle-hash with autoplay

### ISSUE THREAD

**Issue by CarineWednesday** [malsup/cycle2#7]
Hi Malsup,

Firstly I would like to thank you for your continued work. Cycle has always been my slideshow plugin of choice and the release of cycle2 is really a dream come true!

I was wondering why using data-cycle-hash on the slides cause the autoplay to not work?

For the original cycle - I used hash change with functions such as:
 onPagerEvent: function (idx, slide) {
            hasSlid = 1;
            window.location.hash = $(slide).data('title');
            return false;
   }

Is there anything that would similarly work?

Many thanks in advance!

**Comment by malsup** [comment]
I believe I just fixed this as you were typing this issue!  :-)   Can you grab latest and retest?

**Comment by CarineWednesday** [comment]
Wow. You are actually amazing. Works for me!

Thank you so much.
