### ISSUE TITLE
Carousel: Carousel-Offset Breaks When Wrapping (And Fix)

### ISSUE THREAD

**Issue by ShaunaGordon** [malsup/cycle2#70]
I have the following set up for a carousel: http://jsfiddle.net/VLLJX/5/

This creates a carousel with three visible items, which overall works well. However, when it wraps around (last to first, or first to last), it seems to ignore the offset. By removing the offset, the wrapping works as expected.

**Comment by ShaunaGordon** [comment]
I found the source of the problem. On https://github.com/malsup/cycle2/blob/master/jquery.cycle2.carousel.js#L239, the offset is calculated by subtracting opts.carouselOffset, when it should be adding opts.carouselOffset. I'll be posting a pull request shortly.

**Comment by malsup** [comment]
Good catch, thanks!
