### ISSUE TITLE
Feature Request: Progressive Pagination

### ISSUE THREAD

**Issue by Krindi** [malsup/cycle2#702]
At present, slideshows with pagers are not supported with the progressive option per final note  on http://jquery.malsup.com/cycle2/demo/progressive.php

This particular feature would be of significant value for my company's usage, as the vast majority of my slideshows have pagers.  (Presently it works in a sub-optimal fashion: the pager dots appear as each slide is transitioned to, defeating the use of the pager dots as they won't all appear until the slideshow has cycled through fully once.)

**Comment by ghost** [comment]
Me too!

**Comment by Krindi** [comment]
Found prior feature request, closing this issue and commenting there.
