### ISSUE TITLE
How to go back to first image after ending the loop automatically

### ISSUE THREAD

**Issue by doubledigit** [malsup/cycle2#727]
Hi Mike,
Thanks for sharing your cycle2 plugin. 

I have a loop of images. Just cycling once and then it stops at the last. How can I make it return to the first slide automatically, without using 'allow-wrap'. Their should be an easy way to do that, but I couldn't find it. 

I don't understand javascript, but if you could explain what to do and where to put that script, I do appreciate that. Thank you for your help.
Felix

**Comment by makbeta** [comment]
Felix did you try setting data-cycle-loop="1" in your slideshow settings? That should do the trick.

**Comment by doubledigit** [comment]
Hello makbeta,

Yes, I had this already done, but I had changed some other settings as well, and had to reverse that.. 
Thanks for the reply, now this is solved.

Felix
