### ISSUE TITLE
Clicking on next / prev button stop current transition

### ISSUE THREAD

**Issue by Sybio** [malsup/cycle2#73]
Hello Malsup,

I'm trying to find out how to don't stop a transition in progress when a user click on the next (or prev) button. Currently, it stop the transition animation and launch the transition of the next slide.

If we click multiple time on the next button, it will roughly stop transitions...

Is there a way to disable this effect and force to wait the end of a transition ?

Firsttly, I tried to define data-cycle-data-cycle-sync="false" but I have probably misunderstood this function.

Anyway, your plugin is really awesome and flexible thanks !

**Comment by malsup** [comment]
You can now do this:

```
<div class="cycle-slideshow" data-cycle-manual-trump=false> ...
```

or:

```
$('.cycle-slideshow').cycle({
    manualTrump: false,
    ...
})
```

**Comment by Sybio** [comment]
Really excellent !
Works fine, will update it on all my websites thank you very much !

**Comment by nicksantan** [comment]
Hi there,

I'm wondering if there's a way to keep a user from clicking 'next' or 'prev' repeatedly... thus interrupting the transitions they already initiated. Doing so is breaking my slideshow. I would love it if a user could not click 'next' or 'prev' until the transition finished, but it seems as though manualTrump only works for manual transitions vs. scripted transitions.
