### ISSUE TITLE
Allow slides to request additional display time

### ISSUE THREAD

**Issue by lilith** [malsup/cycle2#78]
I'm looking for a way to markup certain slides to display for a different amount of time than normal; generally the first and last slide - but not always.

I don't need to change the transition time, just the display time.

Is there an existing method for doing this?

**Comment by malsup** [comment]
Use the "timeout" option on the slide elements to override the default slideshow timeout:

```
<div class="cycle-slideshow" data-cycle-timeout=3000>
    <img src="1.png" data-cycle-timeout=5000>
    <img src="2.png">
    <img src="3.png">
    <img src="4.png">
    <img src="5.png" data-cycle-timeout=5000>
</div>
```

**Comment by lilith** [comment]
Thanks! Is there a doc on this somewhere?

**Comment by malsup** [comment]
http://jquery.malsup.com/cycle2/api/#timeout

Red bullet means it's overridable on the slide element.  :-)

**Comment by lilith** [comment]
Wow, thanks, I totally missed that. I think I have everything else memorized :)
