### ISSUE TITLE
allow-wrap

### ISSUE THREAD

**Issue by Minasokoni** [malsup/cycle2#79]
I dont use the data- attr for my slides I use the old fashioned js technique. Is 'allow-wrap' not an option for people who us it in their js?

**Comment by Minasokoni** [comment]
Never mind I checked the source. its 'allowWrap' if anyone is interested

**Comment by ralves-dev** [comment]
> Options can also be set programatically if you prefer, by passing an options hash to the cycle method. When setting options programmically the option name does not contain the data-cycle- prefix and the string is camelCased on hyphens:

in [api documentation](http://jquery.malsup.com/cycle2/api/)
