### ISSUE TITLE
carousel apparently breaks text wrapping

### ISSUE THREAD

**Issue by ghost** [malsup/cycle2#8]
in some cases if text would normally wrap in a slideshow element, it overflows insiead of wrapping, if carusel is used.
see:
 http://dl.dropbox.com/u/4130873/it-modalrnd2b.html
the text wraps normally if carousel is disabled in this slideshow 
testedin ff and ie.
here is an anything-slider version of the page, to illustrate what i'm trying to do:
http://dl.dropbox.com/u/4130873/it-modalrnd-as.html

**Comment by malsup** [comment]
For the carousel effect, the slides are wrapped in a div with the white-space:nowrap style and your slides are inheriting this.  In your case, you can correct this by applying a style override on your &lt;li&gt; items:  white-space:normal

**Comment by ghost** [comment]
surprisingly, still the same result with li{white-space:normal}
see
http://dl.dropbox.com/u/4130873/it-modalrnd2b.html

**Comment by malsup** [comment]
You forgot a semi-colon.

**Comment by ghost** [comment]
oh! 
my bad! 
now works perfectly; thanks!

**Comment by ghost** [comment]
now works perfectly in ff but has new whitespae issues in chome (but not ff or ie)
as before, things work  normally if carousel is disabled 
doing more tests to see what's up.
will report further

**Comment by ghost** [comment]
chrome looses the li height
ie8 miscalculates horiz so previous page creeps in as ss progresses
http://dl.dropbox.com/u/4130873/it-modalrnd2b.html

**Comment by malsup** [comment]
Closing this issue.  Please create new ticket if there is still something wrong.  Thanks.
