### ISSUE TITLE
why do some options in the options object passed to .cycle() have an - in them?

### ISSUE THREAD

**Issue by koenverburg** [malsup/cycle2#806]
Im trying to get swiping to work, but `swipe-fx` will cause an error like `SyntaxError: missing : after property id`
this is mainly caused by the `-` in the variable name.

my code 
```javascript
            $(".js-cycle-slideshow").cycle({
                allow-wrap: false,
                loop: 1,
                swipe: true,
                slides: "> .urenSchema-dag",
                //manual-fx: "scrollHorz"
                //swipeFx: "scrollHorz"
                timeout: 0
                
            });
```

**Comment by gabrielfin** [comment]
The "-" version is only if you pass the options through html attributes. ie: `<div data-cycle-allow-wrap="false">`
If you want to pass the options to the javascript function, you need to convert them to camelcase. In this case: `allowWrap: false`
http://jquery.malsup.com/cycle2/api/#options

**Comment by koenverburg** [comment]
Thanks for clarifying!!
