### ISSUE TITLE
Carousel Pager Doesn't Advance Through All Slides

### ISSUE THREAD

**Issue by ryanswedal** [malsup/cycle2#83]
Using the next button on the Carousel Pager only advances to slide 5. The expected behavior would be that it would continue advancing to the last slide.

http://jquery.malsup.com/cycle2/demo/caro-pager.php

**Comment by oakley808** [comment]
Confirmed this is a bug. 

The carousel "next" button is getting the class ".disabled" added to it on slide 5.

**Comment by malsup** [comment]
This is due to the <code>data-allow-wrap="false"</code>

**Comment by lacmo** [comment]
but set data-allow-wrap="ture", the pager slide index will be error

**Comment by neilmonroe** [comment]
I understand this is closed, but is there another way to accomplish what the original poster is describing? Or a fix to this functionality built into the cycle plugin?

**Comment by ryanswedal** [comment]
Just to re-iterate so maybe this issue gets re-opened.

If the carousel pager is set to allow-wrap=false then the prev and next buttons only advance until the final set of thumbnails are showing but then stops when it reaches the first thumbnail in the final set. The expected behavior would be for the next button to continue through the thumbnails one by one until the final thumbnail.

So for the example (http://jquery.malsup.com/cycle2/demo/caro-pager.php) you would expect the next button to continue to advance through the individual thumbnails until it reaches 9 of 9. However, it stops at 5 because the remaining thumbnails are now visible.

If the carousel pager is set to allow-wrap=true then the thumbnails are no longer clickable.

I love this plugin and it has been my preferred slideshow plugin for some time now. I would love to get this fixed because I am getting more and more requests for this kind of carousel pager. I will definitely donate some money to the author if this gets fixed.

Other post about the same issue:
https://github.com/malsup/cycle2/issues/464
https://github.com/malsup/cycle2/issues/449

**Comment by jrthib** [comment]
Yeah this is still an issue. Not sure why the issue is closed...

**Comment by wlanni** [comment]
Hey folks, anyone make progress on this? I'm running into it as well:
Carousel up via a function (not using data- in element)

I'm looking for the same things:
1. Pager "disabled" state gets wonky. Doesn't know it should be disabled
2. Previous button allows you to move backwards through visible items, and then begins paging automatically. Next button allows you to go forward, but then stops working (and doesn't throw 'disabled' once the last carousel item is visible

```
fx:                 'carousel',
timeout:            0,
carouselVisible:    8,
carouselFluid:      true,
caption:            '#exhibition-carousel-caption',
captionTemplate:    "<small><strong>Item {{slideNum}} of {{slideCount}}</strong></small>",
swipe:              true,
pagerEvent:         'click.cycle',
updateView:         1,
autoHeight:         'calc',
allowWrap:          false,
next:               "#exhibition-carousel-right",
prev:               "#exhibition-carousel-left",
slides:             ">figure",
updateView:         1,
pauseOnHover:       true
```

**Comment by theswebsite** [comment]
I had the same problem but seem to have found a solution.

I assigned each of my thumbnails in the pager a data-hard-index value. I set this to the index number of the slide. Therefore when cycle2 duplicates the thumbnail it also duplicates this value.

You can then write a simple jQuery function using the .cycle('goto') function.

``` javascript
$('body').on("click", "#pager .cycle-slide", function() {
    var strIndex = $(this).attr('data-hard-index');
    console.log('Update index to ' + strIndex);
    $(".main-cycle").cycle('goto', strIndex);
});
```

Hope this helps anyone who had the same issue.

**Comment by sweintraub** [comment]
My solution for this is to completely decouple the built-in prev/next function, and build it out manually in JS. The basis is to do what @theswebsite did above, by assigning static data-indexes to each pager slide. Then I just have it advance manually up or down from the current index, and go to the current main slide as well. It's ugly, but works.

Here's a simplified example. To make it really work well, you'd want a separate function to control the active/disabled states for visual feedback.

```javascript
$(".prev, .next").on("click", function(){
    var index = pager.find(".cycle-slide-active").data("index");
    if($(this).hasClass("next")){
      index = index + 1
    } else {
      index = index - 1
    }
    pager.cycle('goto', index);
    slides.cycle('goto', index);
  });
```

**Comment by shanifelder** [comment]
I ended up removing the **data-cycle-carousel-visible** attribute altogether and it's working.
