### ISSUE TITLE
Fade #prev and #next Buttons

### ISSUE THREAD

**Issue by kaspar-allenbach** [malsup/cycle2#84]
Hi
Is it somehow possible to fadeIn the directional buttons when hover over the slideshow?

Thank you

**Comment by mpettitt** [comment]
Try playing with the transition effects: adding "transition: all 1s;" to the .cycle-next and .cycle-prev classes will give you a fade in and out effect in modern browsers, given the style on the demo page which is adjusting the opacity.
Alternatively, you could listen to mouseover events and control the fading yourself, although this probably won't be as smooth, and means extra code on the page.

**Comment by malsup** [comment]
@mpettitt offers some good ideas.  Basically your question has nothing to do with Cycle itself, not that it's a bad question, it's just outside the scope of what the plugin provides.

**Comment by kaspar-allenbach** [comment]
Hi. Yeah right. Thanks I didn't taught about css transition. I taught there might be some trigger inside the cycle plugin.
Thanks for your answers.
