### ISSUE TITLE
problem with wordpress/php

### ISSUE THREAD

**Issue by GodShin** [malsup/cycle2#841]
I tried the basic example from the demo page but the the pictures are just underneath one another.  I think I did load the script correctly in the functions.php file:

`function my_theme_scripts() {
    wp_enqueue_script( 'mycycle2', 'http://malsup.github.com/jquery.cycle2.js', array( 'jquery' )
);
}
add_action( 'wp_enqueue_scripts', 'my_theme_scripts' );`

and in the actual slider I just wrote (it shows as the pictures)
Have I made a basic php or wordpress mistake? I cant find any useful information
so I would be very grateful for any tips

<div class="cycle-slideshow">
    <img src="http://malsup.github.io/images/p1.jpg">
    <img src="http://malsup.github.io/images/p2.jpg">
    <img src="http://malsup.github.io/images/p3.jpg">
    <img src="http://malsup.github.io/images/p4.jpg">
</div>

**Comment by prbenson** [comment]
Do you have a URL running this live for review?

**Comment by GodShin** [comment]
It's under https://demokratietalk.at/

**Comment by prbenson** [comment]
I think the browser is blocking the js script because your site is on
https. Try changing your code to use this instead:

'https://malsup.github.com/jquery.cycle2.js'

Let me know if that fixes it!

**Comment by prbenson** [comment]
Or you can use this URL instead:

https://cdnjs.cloudflare.com/ajax/libs/jquery.cycle2/2.1.6/jquery.cycle2.js

**Comment by GodShin** [comment]
Thanks, the second url worked :-)
Do you have any idea why the other one (I tried with https) didn't?

Thanks again!

**Comment by prbenson** [comment]
It is odd as I noticed the same thing and I'm not sure. You can also store
the js file on your hosting server.

Hallo aus America!  Lass mich wissen, ob ich noch etwas tun kann zu helfen!

**Comment by GodShin** [comment]
Danke, vielleicht stoße ich mal auf die Antwort!

Schöne Grüße aus Österreich!
Greetings from Austria!
