### ISSUE TITLE
Is there an event which only relates to an automatic transition?

### ISSUE THREAD

**Issue by cx99** [malsup/cycle2#85]
Hi,

I am using the 'cycle-before' event to change something in sync with the slideshow. It also finds information from the next slide.

However I'm also using the cycle-pager, which needs to work differently because it is not looking for the next slide (syntactically) but rather the target slide. This is fine, I have set it to work differently.

But if I click a link in the pager, it also initiates the cycle-before event.

Is there an option for cycle-before, or another event, which only responds to the _automated_ slideshow transition?

Great plugin btw thank you

**Comment by malsup** [comment]
cycle-before/cycle-after/cycle-update-view always trigger regardless of how the transition was initiated.  You could listen for the cycle-pager-activated event which only fires when a pager link is clicked.

**Comment by cx99** [comment]
Ah thanks but I think this is the opposite if what I mean, I was hoping for something which doesn't trigger always or with the pager - _only_ when the slideshow progresses by itself.

**Comment by malsup** [comment]
I understand, but C2 doesn't have a timer-only event.

**Comment by cx99** [comment]
Understood, thanks for the quick response, again thanks for the great plugin
