### ISSUE TITLE
Problem with pagers

### ISSUE THREAD

**Issue by 812402** [malsup/cycle2#87]
I have been setting up a slideshow for my website and the pagers are not working. When the page loads in, it shows 2 little black bullets bellow the slideshow, which I'm guessing is supposed to be the pagers, then after the next slide appears, they disappear.  Here is my HTML: 
        <div id ="container" align="center">
            <div id="main">
                <br>
                <div class="cycle-slideshow"
                    data-cycle-fx=scrollHorz
                    data-cycle-timeout=5000 
                    align="center" id="slideshow">
                    
                    <div class="cycle-pager">
                    </div>

```
                <img src="test.jpg">
                <img src="test2.jpg">
            </div>
        </div>
    </div>
```

Please help! Any help is appreciated greatly. Thanks!

-812402

**Comment by malsup** [comment]
You need to provide appropriate styles for the pagers.  For example:

http://jquery.malsup.com/cycle2/demo/demo-slideshow.css

**Comment by 812402** [comment]
Thanks for the help, but I had already tried that. I was messing around with the style and found that if I got rid of the overflow: hidden, it worked. I don't know why, but it did. Maybe me website is messed up =P.

**Comment by texelate** [comment]
I know this is old but I'll comment anyway in case anyone else has this issue.

The problem occurs when your pager and/or prev/next links are children of `div.cycle-slideshow`. Once you click a link if you are using an animation that involves animating content from outside the element (e.g. **scrollHorz**) the overflow kicks in and you can no longer see anything outside of `div.cycle-slideshow`. Forcing visible overflow won't work as you'll get unwanted content around your main element.

To fix you need to simply forgo cycle2's automatic pager and link detection and instead place them _outside_ of `div.cycle-slideshow` — and set the `data-cycle-prev` and `data-cylce-next` properties to explicitly tell it where to find them.
