### ISSUE TITLE
Non-Image-Sideshow Transparency

### ISSUE THREAD

**Issue by kaspar-allenbach** [malsup/cycle2#90]
Hi.

I made a synced cycle-slideshow.

One is with text, the other is with an image.
Now the thing is, in order to show the background pattern I can't give the cycle div's a background.

So the text from all slides is visible. This doesn't look very solid. ;)
Is it possible to make only the front div visible?

Here you can see it live: http://sonjamuehlemann.ch/

Thank you

**Comment by FlashJunior** [comment]
before you debug, you shoud fix your html errors.
 Duplicate attribute data-reveal-id, No space between attributes, Quote " in attribute name...
...

one example:

```
<img
alt="Habit of a Rabbit - Albumteaser "Voodoo"" src="/images/made/images/uploads/bilder/Sequenz_2_310_220_90_c1.jpg">
```

that shoud be:

```
<img alt="Habit of a Rabbit" src="/images/made/images/uploads/bilder/Sequenz_2_310_220_90_c1.jpg" />
```

i use https://addons.mozilla.org/de/firefox/addon/html-validator/ to validate. But you can also use http://validator.w3.org

**Comment by kaspar-allenbach** [comment]
Hi. Thanks for the advice. Although the error wasn't in the html Markup. It was the Typekit Webfont-loader.
In order to prevent the flash of unstiled text (FOUT) all fonts are made visible after the webfont has loaded.

The webfont loader then applies "visibility: visible;" to all typography which prevents cycle to do it's job. Disabled the Webfont asynchronous loading behavior and now it works. But now I have the FOUT again :(

**Comment by malsup** [comment]
The default behavior is to hide non-active slides.  What version of cycle are you using?

**Comment by malsup** [comment]
I just checked your link, looks like you have it working ok.
