### ISSUE TITLE
tcycle with carousel plugin

### ISSUE THREAD

**Issue by Colir** [malsup/cycle2#92]
HI, first at all,
I'm very exiting :
I'm a fair user of the cycle plugin, and i just discover this V.2. I'm really enjoy it.

I have a little question : Can we use The tCycle plugin (the tiny one) with the cycle2 - carousel plugin ?

thanks a lot

**Comment by malsup** [comment]
No, tCycle is just a stand-alone fader/slider.  It doesn't support plugins.

**Comment by Colir** [comment]
ok, thanks.
