### ISSUE TITLE
Progressive Loading / Looping

### ISSUE THREAD

**Issue by mjcampagna** [malsup/cycle2#95]
Hi Malsup,

I tweeted at you, but only just found my way to the github support, so thought my question might be more appropriately asked here.

I'm running a slideshow with the following options:

```
data-cycle-auto-height="false" 
data-cycle-fx="fade" 
data-cycle-log="false"
data-cycle-loop="0" 
data-cycle-progressive="#slides" 
data-cycle-slides=">div" 
data-cycle-speed="200" 
data-cycle-timeout="500" 
```

Enabling data-cycle-progressive seems to have killed my slideshow looping; the slideshow just stops on reaching the final slide. Is this a known issue, or is there a workaround I've missed?

Thanks,
Matt

**Comment by mjcampagna** [comment]
And I have just found that manually clicking the "Next" button to advance the slideshow from that point will advance back to the first slide, and thereafter the slideshow loops properly. Hoping this helps to shed some additional light on the issue.

**Comment by malsup** [comment]
I'm not able to duplicate this issue.

http://jquery.malsup.com/cycle2/demo/issue-95.php

Also, usually you'd want to also use the "loader" option when using the progressive option.

**Comment by mjcampagna** [comment]
Hi Malsup,

Thanks for the reply. Your attention is much appreciated. Here's a gallery exhibiting the problem:
http://test.theturninggate.net/cycle/

There's 10 images; the last one is the guy standing in front of the boat waving. And you will see that the slideshow stops at that point. There is an error in the console log, but it's reporting the problem as being in jQuery itself -- "Uncaught Error: The specified default tab ('li:first-child') could not be found in the tab set." in the jquery-1.8.2.min.js file -- so I'm not sure what to make of it or how to solve it, i.e. I don't know whether this is a jQuery bug, or a cycle bug that's triggering the problem. It seems to want li:first-child, but as I am using data-cycle-slides=">div", should it not be looking for div:first-child?

**Comment by malsup** [comment]
I can't help when you use the minified version and have logging disabled.  The js error has nothing to do with cycle, it looks to be something with easytabs.  But again, you have a test page setup but are using all minified script.

**Comment by mjcampagna** [comment]
Hi,

Sorry about that. Was posting the demo late at night here in a rush, before going to bed. I had meant to enable logging at least, and forgot to do so. I've updated the demo:
http://test.theturninggate.net/cycle/

Re-inserted a menu item, so easyTabs doesn't get upset. Swapped Cycle2 for the development version. Enabled logging. Please let me know if I can do anything else to make this easier. Again, I appreciate your help.

Cheers,
Matt

**Comment by mjcampagna** [comment]
It occurred to me today what the problem may be, and sure enough that was the cause. I was using the delimiter method of defining slides, data-cycle-split="---", and there was a --- after my final slide. So I guess the slideshow was looking for another slide that wasn't there.

**Comment by malsup** [comment]
Thanks for the update.  That sounds like a case I should be checking for in the code.
