### ISSUE TITLE
Resize container based on current slide height

### ISSUE THREAD

**Issue by benfoster** [malsup/cycle2#98]
Perhaps I've misunderstood the "auto height" feature of cycle2.

I have a sequence of images of varying height with Next/Prev pager below. I would like the pager buttons to "stick" to the bottom of the slideshow container when the images change.

I've tried both the default and "calc" setting, the first of which sets the height of the container to the first image and the latter setting the height to the largest image.

Is there a setting to set the height of the container based on the height of the **current** image?

**Comment by albell** [comment]
First, this is arguably a terrible idea from a user experience perspective. For example, if you have pager buttons below the slideshow, do you really want your user to have to hunt all over the page to get to the "next" button each and every time an new slide loads? This gets tedious _real_ fast. And you want all your content below the slideshow to reflow on each transition?  It's a pretty serious distraction from your content, sending your user on a pointless game of hide and seek in between each transition. It's much nicer to the use to let him rest his mouse (or finger) in the same spot, when clicking through a pager. Mike has put enormous thought into making sure what you're describing _doesn't_ happen!

But I digress.  It's your site, and maybe there's a good reason for the behavior you're describing. Just listen for the next "cycle-before" event, which fires off just prior to a transition to a new slide, get the height of the incoming slide, and set the parent container's height to that dimension. Something like this:

$( '#mySlideshow').on( 'cycle-before', function(event, optionHash, outgoingSlideEl, incomingSlideEl, forwardFlag) {
    var incomingHeight = $(incomingSlideEl).innerHeight();
    $(this).height(incomingHeight);
});

or you could be fancy and animate the height in CSS with jquery, matching the duration of your transitions. Hope this helps.

**Comment by malsup** [comment]
Demo:  http://jquery.malsup.com/cycle2/demo/container-resize.php

**Comment by webchimp** [comment]
Hey @malsup thanks! JFYI, Placekitten is not loading so the example is not working.

**Comment by chumpynut** [comment]
I am attempting to use data-cycle-auto-height=container argument, but it doesn't seem to work for me. There is a difference between the height of the slideshow container and the image. I was assuming the container would adjust to the image height. There appears a small gap below the image. The URL illustrating the issue is http://guidewireservices.com/staging1/properties/1720-fairmount/.

Thanks in advance.
