### ISSUE TITLE
Nothing work in async mode  

### ISSUE THREAD

**Issue by deryost** [malsup/cycle2#99]
I'm testing in google Chrome.
I'm loading scripts dynamically, if needed.
When doing so, cycle2 Auto-Initialization seem to work, I have log entries from the console.
But the slideshow doesn't start, and the next and previous button doesn't work either.

If I use manual initiation, it work.

If I put my script in my HTML, it work. But if I add the async attribute to the cycle2 plugin, I have the same  problem again.

Good work by the way !

**Comment by albell** [comment]
That might just be the correct behavior. Re-read the first paragraph of the API, under Auto-initialization:

http://www.malsup.com/jquery/cycle2/api/

Some questions:
1) What are you getting in the console exactly?
2 ) Are you _absolutely_ sure that both the slideshows and previous/next buttons are part of the DOM at the moment when cycle2 is being loaded/called? You need to be very precise with your callback structure if you're going all the way async.
3) Are the cycle2 classes being added to your slide elements?

The quick and easy way to deal with this might be just to (possibly redundantly) call cycle manually as a callback to your ajax load: "Cycle2 will not re-initialize a running slideshow if you invoke cycle on it more than once. So it is perfectly safe to run the code above multiple times without having to worry about slideshows that are already running."

**Comment by deryost** [comment]
Well I did the quick and easy way to make it work without changing anything.
But I remove the default auto-initialization class for mine.

The bug was maybe the dom not ready.
